/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedditRouteImport } from './routes/reddit'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as ApiSubredditsIndexRouteImport } from './routes/api/subreddits/index'
import { Route as ApiPipelineIndexRouteImport } from './routes/api/pipeline/index'
import { Route as ApiKeywordsIndexRouteImport } from './routes/api/keywords/index'
import { Route as ApiBlogIndexRouteImport } from './routes/api/blog/index'
import { Route as ApiSubredditsIdRouteImport } from './routes/api/subreddits/$id'
import { Route as ApiRedditSuggestRouteImport } from './routes/api/reddit/suggest'
import { Route as ApiRedditSearchRouteImport } from './routes/api/reddit/search'
import { Route as ApiRedditPostsRouteImport } from './routes/api/reddit/posts'
import { Route as ApiPipelineLeadsRouteImport } from './routes/api/pipeline/leads'
import { Route as ApiLinkedinSearchRouteImport } from './routes/api/linkedin/search'
import { Route as ApiLinkedinGeneratePostRouteImport } from './routes/api/linkedin/generate-post'
import { Route as ApiKeywordsIdRouteImport } from './routes/api/keywords/$id'
import { Route as ApiEmailSendRouteImport } from './routes/api/email/send'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard/stats'
import { Route as ApiBlogGenerateRouteImport } from './routes/api/blog/generate'
import { Route as ApiBlogIdRouteImport } from './routes/api/blog/$id'
import { Route as ApiAgentRunRouteImport } from './routes/api/agent/run'
import { Route as ApiPipelineLeadsIdRouteImport } from './routes/api/pipeline/leads.$id'

const RedditRoute = RedditRouteImport.update({
  id: '/reddit',
  path: '/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubredditsIndexRoute = ApiSubredditsIndexRouteImport.update({
  id: '/api/subreddits/',
  path: '/api/subreddits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineIndexRoute = ApiPipelineIndexRouteImport.update({
  id: '/api/pipeline/',
  path: '/api/pipeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsIndexRoute = ApiKeywordsIndexRouteImport.update({
  id: '/api/keywords/',
  path: '/api/keywords/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIndexRoute = ApiBlogIndexRouteImport.update({
  id: '/api/blog/',
  path: '/api/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubredditsIdRoute = ApiSubredditsIdRouteImport.update({
  id: '/api/subreddits/$id',
  path: '/api/subreddits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditSuggestRoute = ApiRedditSuggestRouteImport.update({
  id: '/api/reddit/suggest',
  path: '/api/reddit/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditSearchRoute = ApiRedditSearchRouteImport.update({
  id: '/api/reddit/search',
  path: '/api/reddit/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditPostsRoute = ApiRedditPostsRouteImport.update({
  id: '/api/reddit/posts',
  path: '/api/reddit/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineLeadsRoute = ApiPipelineLeadsRouteImport.update({
  id: '/api/pipeline/leads',
  path: '/api/pipeline/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinSearchRoute = ApiLinkedinSearchRouteImport.update({
  id: '/api/linkedin/search',
  path: '/api/linkedin/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinGeneratePostRoute = ApiLinkedinGeneratePostRouteImport.update({
  id: '/api/linkedin/generate-post',
  path: '/api/linkedin/generate-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsIdRoute = ApiKeywordsIdRouteImport.update({
  id: '/api/keywords/$id',
  path: '/api/keywords/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSendRoute = ApiEmailSendRouteImport.update({
  id: '/api/email/send',
  path: '/api/email/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogGenerateRoute = ApiBlogGenerateRouteImport.update({
  id: '/api/blog/generate',
  path: '/api/blog/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIdRoute = ApiBlogIdRouteImport.update({
  id: '/api/blog/$id',
  path: '/api/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRunRoute = ApiAgentRunRouteImport.update({
  id: '/api/agent/run',
  path: '/api/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineLeadsIdRoute = ApiPipelineLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPipelineLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/blog': typeof BlogRoute
  '/keywords': typeof KeywordsRoute
  '/linkedin': typeof LinkedinRoute
  '/pipeline': typeof PipelineRoute
  '/reddit': typeof RedditRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/generate': typeof ApiBlogGenerateRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRoute
  '/api/linkedin/generate-post': typeof ApiLinkedinGeneratePostRoute
  '/api/linkedin/search': typeof ApiLinkedinSearchRoute
  '/api/pipeline/leads': typeof ApiPipelineLeadsRouteWithChildren
  '/api/reddit/posts': typeof ApiRedditPostsRoute
  '/api/reddit/search': typeof ApiRedditSearchRoute
  '/api/reddit/suggest': typeof ApiRedditSuggestRoute
  '/api/subreddits/$id': typeof ApiSubredditsIdRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/keywords/': typeof ApiKeywordsIndexRoute
  '/api/pipeline/': typeof ApiPipelineIndexRoute
  '/api/subreddits/': typeof ApiSubredditsIndexRoute
  '/api/pipeline/leads/$id': typeof ApiPipelineLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/blog': typeof BlogRoute
  '/keywords': typeof KeywordsRoute
  '/linkedin': typeof LinkedinRoute
  '/pipeline': typeof PipelineRoute
  '/reddit': typeof RedditRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/generate': typeof ApiBlogGenerateRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRoute
  '/api/linkedin/generate-post': typeof ApiLinkedinGeneratePostRoute
  '/api/linkedin/search': typeof ApiLinkedinSearchRoute
  '/api/pipeline/leads': typeof ApiPipelineLeadsRouteWithChildren
  '/api/reddit/posts': typeof ApiRedditPostsRoute
  '/api/reddit/search': typeof ApiRedditSearchRoute
  '/api/reddit/suggest': typeof ApiRedditSuggestRoute
  '/api/subreddits/$id': typeof ApiSubredditsIdRoute
  '/api/blog': typeof ApiBlogIndexRoute
  '/api/keywords': typeof ApiKeywordsIndexRoute
  '/api/pipeline': typeof ApiPipelineIndexRoute
  '/api/subreddits': typeof ApiSubredditsIndexRoute
  '/api/pipeline/leads/$id': typeof ApiPipelineLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/blog': typeof BlogRoute
  '/keywords': typeof KeywordsRoute
  '/linkedin': typeof LinkedinRoute
  '/pipeline': typeof PipelineRoute
  '/reddit': typeof RedditRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/generate': typeof ApiBlogGenerateRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRoute
  '/api/linkedin/generate-post': typeof ApiLinkedinGeneratePostRoute
  '/api/linkedin/search': typeof ApiLinkedinSearchRoute
  '/api/pipeline/leads': typeof ApiPipelineLeadsRouteWithChildren
  '/api/reddit/posts': typeof ApiRedditPostsRoute
  '/api/reddit/search': typeof ApiRedditSearchRoute
  '/api/reddit/suggest': typeof ApiRedditSuggestRoute
  '/api/subreddits/$id': typeof ApiSubredditsIdRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/keywords/': typeof ApiKeywordsIndexRoute
  '/api/pipeline/': typeof ApiPipelineIndexRoute
  '/api/subreddits/': typeof ApiSubredditsIndexRoute
  '/api/pipeline/leads/$id': typeof ApiPipelineLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/blog'
    | '/keywords'
    | '/linkedin'
    | '/pipeline'
    | '/reddit'
    | '/settings/profile'
    | '/api/agent/run'
    | '/api/blog/$id'
    | '/api/blog/generate'
    | '/api/dashboard/stats'
    | '/api/email/send'
    | '/api/keywords/$id'
    | '/api/linkedin/generate-post'
    | '/api/linkedin/search'
    | '/api/pipeline/leads'
    | '/api/reddit/posts'
    | '/api/reddit/search'
    | '/api/reddit/suggest'
    | '/api/subreddits/$id'
    | '/api/blog/'
    | '/api/keywords/'
    | '/api/pipeline/'
    | '/api/subreddits/'
    | '/api/pipeline/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/blog'
    | '/keywords'
    | '/linkedin'
    | '/pipeline'
    | '/reddit'
    | '/settings/profile'
    | '/api/agent/run'
    | '/api/blog/$id'
    | '/api/blog/generate'
    | '/api/dashboard/stats'
    | '/api/email/send'
    | '/api/keywords/$id'
    | '/api/linkedin/generate-post'
    | '/api/linkedin/search'
    | '/api/pipeline/leads'
    | '/api/reddit/posts'
    | '/api/reddit/search'
    | '/api/reddit/suggest'
    | '/api/subreddits/$id'
    | '/api/blog'
    | '/api/keywords'
    | '/api/pipeline'
    | '/api/subreddits'
    | '/api/pipeline/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/blog'
    | '/keywords'
    | '/linkedin'
    | '/pipeline'
    | '/reddit'
    | '/settings/profile'
    | '/api/agent/run'
    | '/api/blog/$id'
    | '/api/blog/generate'
    | '/api/dashboard/stats'
    | '/api/email/send'
    | '/api/keywords/$id'
    | '/api/linkedin/generate-post'
    | '/api/linkedin/search'
    | '/api/pipeline/leads'
    | '/api/reddit/posts'
    | '/api/reddit/search'
    | '/api/reddit/suggest'
    | '/api/subreddits/$id'
    | '/api/blog/'
    | '/api/keywords/'
    | '/api/pipeline/'
    | '/api/subreddits/'
    | '/api/pipeline/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  BlogRoute: typeof BlogRoute
  KeywordsRoute: typeof KeywordsRoute
  LinkedinRoute: typeof LinkedinRoute
  PipelineRoute: typeof PipelineRoute
  RedditRoute: typeof RedditRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  ApiAgentRunRoute: typeof ApiAgentRunRoute
  ApiBlogIdRoute: typeof ApiBlogIdRoute
  ApiBlogGenerateRoute: typeof ApiBlogGenerateRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiEmailSendRoute: typeof ApiEmailSendRoute
  ApiKeywordsIdRoute: typeof ApiKeywordsIdRoute
  ApiLinkedinGeneratePostRoute: typeof ApiLinkedinGeneratePostRoute
  ApiLinkedinSearchRoute: typeof ApiLinkedinSearchRoute
  ApiPipelineLeadsRoute: typeof ApiPipelineLeadsRouteWithChildren
  ApiRedditPostsRoute: typeof ApiRedditPostsRoute
  ApiRedditSearchRoute: typeof ApiRedditSearchRoute
  ApiRedditSuggestRoute: typeof ApiRedditSuggestRoute
  ApiSubredditsIdRoute: typeof ApiSubredditsIdRoute
  ApiBlogIndexRoute: typeof ApiBlogIndexRoute
  ApiKeywordsIndexRoute: typeof ApiKeywordsIndexRoute
  ApiPipelineIndexRoute: typeof ApiPipelineIndexRoute
  ApiSubredditsIndexRoute: typeof ApiSubredditsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reddit': {
      id: '/reddit'
      path: '/reddit'
      fullPath: '/reddit'
      preLoaderRoute: typeof RedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subreddits/': {
      id: '/api/subreddits/'
      path: '/api/subreddits'
      fullPath: '/api/subreddits/'
      preLoaderRoute: typeof ApiSubredditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/': {
      id: '/api/pipeline/'
      path: '/api/pipeline'
      fullPath: '/api/pipeline/'
      preLoaderRoute: typeof ApiPipelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords/': {
      id: '/api/keywords/'
      path: '/api/keywords'
      fullPath: '/api/keywords/'
      preLoaderRoute: typeof ApiKeywordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/': {
      id: '/api/blog/'
      path: '/api/blog'
      fullPath: '/api/blog/'
      preLoaderRoute: typeof ApiBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subreddits/$id': {
      id: '/api/subreddits/$id'
      path: '/api/subreddits/$id'
      fullPath: '/api/subreddits/$id'
      preLoaderRoute: typeof ApiSubredditsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/suggest': {
      id: '/api/reddit/suggest'
      path: '/api/reddit/suggest'
      fullPath: '/api/reddit/suggest'
      preLoaderRoute: typeof ApiRedditSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/search': {
      id: '/api/reddit/search'
      path: '/api/reddit/search'
      fullPath: '/api/reddit/search'
      preLoaderRoute: typeof ApiRedditSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/posts': {
      id: '/api/reddit/posts'
      path: '/api/reddit/posts'
      fullPath: '/api/reddit/posts'
      preLoaderRoute: typeof ApiRedditPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/leads': {
      id: '/api/pipeline/leads'
      path: '/api/pipeline/leads'
      fullPath: '/api/pipeline/leads'
      preLoaderRoute: typeof ApiPipelineLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/search': {
      id: '/api/linkedin/search'
      path: '/api/linkedin/search'
      fullPath: '/api/linkedin/search'
      preLoaderRoute: typeof ApiLinkedinSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/generate-post': {
      id: '/api/linkedin/generate-post'
      path: '/api/linkedin/generate-post'
      fullPath: '/api/linkedin/generate-post'
      preLoaderRoute: typeof ApiLinkedinGeneratePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords/$id': {
      id: '/api/keywords/$id'
      path: '/api/keywords/$id'
      fullPath: '/api/keywords/$id'
      preLoaderRoute: typeof ApiKeywordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/send': {
      id: '/api/email/send'
      path: '/api/email/send'
      fullPath: '/api/email/send'
      preLoaderRoute: typeof ApiEmailSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/generate': {
      id: '/api/blog/generate'
      path: '/api/blog/generate'
      fullPath: '/api/blog/generate'
      preLoaderRoute: typeof ApiBlogGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$id': {
      id: '/api/blog/$id'
      path: '/api/blog/$id'
      fullPath: '/api/blog/$id'
      preLoaderRoute: typeof ApiBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/run': {
      id: '/api/agent/run'
      path: '/api/agent/run'
      fullPath: '/api/agent/run'
      preLoaderRoute: typeof ApiAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/leads/$id': {
      id: '/api/pipeline/leads/$id'
      path: '/$id'
      fullPath: '/api/pipeline/leads/$id'
      preLoaderRoute: typeof ApiPipelineLeadsIdRouteImport
      parentRoute: typeof ApiPipelineLeadsRoute
    }
  }
}

interface ApiPipelineLeadsRouteChildren {
  ApiPipelineLeadsIdRoute: typeof ApiPipelineLeadsIdRoute
}

const ApiPipelineLeadsRouteChildren: ApiPipelineLeadsRouteChildren = {
  ApiPipelineLeadsIdRoute: ApiPipelineLeadsIdRoute,
}

const ApiPipelineLeadsRouteWithChildren =
  ApiPipelineLeadsRoute._addFileChildren(ApiPipelineLeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  BlogRoute: BlogRoute,
  KeywordsRoute: KeywordsRoute,
  LinkedinRoute: LinkedinRoute,
  PipelineRoute: PipelineRoute,
  RedditRoute: RedditRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  ApiAgentRunRoute: ApiAgentRunRoute,
  ApiBlogIdRoute: ApiBlogIdRoute,
  ApiBlogGenerateRoute: ApiBlogGenerateRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiEmailSendRoute: ApiEmailSendRoute,
  ApiKeywordsIdRoute: ApiKeywordsIdRoute,
  ApiLinkedinGeneratePostRoute: ApiLinkedinGeneratePostRoute,
  ApiLinkedinSearchRoute: ApiLinkedinSearchRoute,
  ApiPipelineLeadsRoute: ApiPipelineLeadsRouteWithChildren,
  ApiRedditPostsRoute: ApiRedditPostsRoute,
  ApiRedditSearchRoute: ApiRedditSearchRoute,
  ApiRedditSuggestRoute: ApiRedditSuggestRoute,
  ApiSubredditsIdRoute: ApiSubredditsIdRoute,
  ApiBlogIndexRoute: ApiBlogIndexRoute,
  ApiKeywordsIndexRoute: ApiKeywordsIndexRoute,
  ApiPipelineIndexRoute: ApiPipelineIndexRoute,
  ApiSubredditsIndexRoute: ApiSubredditsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
