/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as WorkspaceIdRouteRouteImport } from './routes/$workspaceId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIdIndexRouteImport } from './routes/$workspaceId/index'
import { Route as WorkspaceIdRedditRouteImport } from './routes/$workspaceId/reddit'
import { Route as WorkspaceIdPipelineRouteImport } from './routes/$workspaceId/pipeline'
import { Route as WorkspaceIdLinkedinPostsRouteImport } from './routes/$workspaceId/linkedin-posts'
import { Route as WorkspaceIdLinkedinRouteImport } from './routes/$workspaceId/linkedin'
import { Route as WorkspaceIdKeywordsRouteImport } from './routes/$workspaceId/keywords'
import { Route as WorkspaceIdDirectoriesRouteImport } from './routes/$workspaceId/directories'
import { Route as WorkspaceIdBlogRouteImport } from './routes/$workspaceId/blog'
import { Route as WorkspaceIdAnalyticsRouteImport } from './routes/$workspaceId/analytics'
import { Route as WorkspaceIdAgentRouteImport } from './routes/$workspaceId/agent'
import { Route as WorkspaceIdSettingsRouteRouteImport } from './routes/$workspaceId/settings/route'
import { Route as ApiTemplatesIndexRouteImport } from './routes/api/templates/index'
import { Route as ApiSubredditsIndexRouteImport } from './routes/api/subreddits/index'
import { Route as ApiPipelineIndexRouteImport } from './routes/api/pipeline/index'
import { Route as ApiKeywordsIndexRouteImport } from './routes/api/keywords/index'
import { Route as ApiCampaignsIndexRouteImport } from './routes/api/campaigns/index'
import { Route as ApiBlogIndexRouteImport } from './routes/api/blog/index'
import { Route as WorkspaceIdTemplatesIndexRouteImport } from './routes/$workspaceId/templates/index'
import { Route as WorkspaceIdSettingsIndexRouteImport } from './routes/$workspaceId/settings/index'
import { Route as WorkspaceIdCampaignsIndexRouteImport } from './routes/$workspaceId/campaigns/index'
import { Route as ApiWorkspaceGenerateDescriptionRouteImport } from './routes/api/workspace/generate-description'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks/resend'
import { Route as ApiWebhooksEmailInboundRouteImport } from './routes/api/webhooks/email-inbound'
import { Route as ApiTemplatesIdRouteImport } from './routes/api/templates/$id'
import { Route as ApiSubredditsIdRouteImport } from './routes/api/subreddits/$id'
import { Route as ApiRedditToPipelineRouteImport } from './routes/api/reddit/to-pipeline'
import { Route as ApiRedditSuggestRouteImport } from './routes/api/reddit/suggest'
import { Route as ApiRedditSearchRouteImport } from './routes/api/reddit/search'
import { Route as ApiRedditPostsRouteImport } from './routes/api/reddit/posts'
import { Route as ApiPipelineLeadsRouteImport } from './routes/api/pipeline/leads'
import { Route as ApiPipelineImportRouteImport } from './routes/api/pipeline/import'
import { Route as ApiPipelineEnrichRouteImport } from './routes/api/pipeline/enrich'
import { Route as ApiLinkedinSearchRouteImport } from './routes/api/linkedin/search'
import { Route as ApiLinkedinGeneratePostRouteImport } from './routes/api/linkedin/generate-post'
import { Route as ApiKeywordsGenerateRouteImport } from './routes/api/keywords/generate'
import { Route as ApiKeywordsIdRouteImport } from './routes/api/keywords/$id'
import { Route as ApiEmailTestSmtpRouteImport } from './routes/api/email/test-smtp'
import { Route as ApiEmailSendRouteImport } from './routes/api/email/send'
import { Route as ApiDirectoriesSearchRouteImport } from './routes/api/directories/search'
import { Route as ApiDirectoriesEnrichRouteImport } from './routes/api/directories/enrich'
import { Route as ApiDirectoriesAddRouteImport } from './routes/api/directories/add'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard/stats'
import { Route as ApiCampaignsSchedulerRouteImport } from './routes/api/campaigns/scheduler'
import { Route as ApiCampaignsProcessDueDraftsRouteImport } from './routes/api/campaigns/process-due-drafts'
import { Route as ApiCampaignsIdRouteImport } from './routes/api/campaigns/$id'
import { Route as ApiBlogGenerateRouteImport } from './routes/api/blog/generate'
import { Route as ApiBlogIdRouteImport } from './routes/api/blog/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentRunRouteImport } from './routes/api/agent/run'
import { Route as WorkspaceIdTemplatesNewRouteImport } from './routes/$workspaceId/templates/new'
import { Route as WorkspaceIdTemplatesTemplateIdRouteImport } from './routes/$workspaceId/templates/$templateId'
import { Route as WorkspaceIdSettingsWorkspaceRouteImport } from './routes/$workspaceId/settings/workspace'
import { Route as WorkspaceIdSettingsProfileRouteImport } from './routes/$workspaceId/settings/profile'
import { Route as WorkspaceIdSettingsEmailRouteImport } from './routes/$workspaceId/settings/email'
import { Route as WorkspaceIdSettingsDangerRouteImport } from './routes/$workspaceId/settings/danger'
import { Route as WorkspaceIdSettingsBillingRouteImport } from './routes/$workspaceId/settings/billing'
import { Route as WorkspaceIdSettingsAppearanceRouteImport } from './routes/$workspaceId/settings/appearance'
import { Route as WorkspaceIdSettingsAgentRouteImport } from './routes/$workspaceId/settings/agent'
import { Route as WorkspaceIdCampaignsNewRouteImport } from './routes/$workspaceId/campaigns/new'
import { Route as WorkspaceIdCampaignsIdIndexRouteImport } from './routes/$workspaceId/campaigns/$id/index'
import { Route as ApiRedditPostsIdRouteImport } from './routes/api/reddit/posts.$id'
import { Route as ApiPipelineLeadsIdRouteImport } from './routes/api/pipeline/leads.$id'
import { Route as ApiCampaignsIdStepsRouteImport } from './routes/api/campaigns/$id/steps'
import { Route as ApiCampaignsIdRunRouteImport } from './routes/api/campaigns/$id/run'
import { Route as ApiCampaignsIdLeadsRouteImport } from './routes/api/campaigns/$id/leads'
import { Route as ApiCampaignsIdGenerateDraftsRouteImport } from './routes/api/campaigns/$id/generate-drafts'
import { Route as ApiCampaignsIdDraftsRouteImport } from './routes/api/campaigns/$id/drafts'
import { Route as ApiCampaignsIdStepsStepIdRouteImport } from './routes/api/campaigns/$id/steps.$stepId'
import { Route as ApiCampaignsIdDraftsDraftIdRouteImport } from './routes/api/campaigns/$id/drafts.$draftId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRouteRoute = WorkspaceIdRouteRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdIndexRoute = WorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdRedditRoute = WorkspaceIdRedditRouteImport.update({
  id: '/reddit',
  path: '/reddit',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdPipelineRoute = WorkspaceIdPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdLinkedinPostsRoute =
  WorkspaceIdLinkedinPostsRouteImport.update({
    id: '/linkedin-posts',
    path: '/linkedin-posts',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const WorkspaceIdLinkedinRoute = WorkspaceIdLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdKeywordsRoute = WorkspaceIdKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdDirectoriesRoute = WorkspaceIdDirectoriesRouteImport.update({
  id: '/directories',
  path: '/directories',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdBlogRoute = WorkspaceIdBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdAnalyticsRoute = WorkspaceIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdAgentRoute = WorkspaceIdAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdSettingsRouteRoute =
  WorkspaceIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const ApiTemplatesIndexRoute = ApiTemplatesIndexRouteImport.update({
  id: '/api/templates/',
  path: '/api/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubredditsIndexRoute = ApiSubredditsIndexRouteImport.update({
  id: '/api/subreddits/',
  path: '/api/subreddits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineIndexRoute = ApiPipelineIndexRouteImport.update({
  id: '/api/pipeline/',
  path: '/api/pipeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsIndexRoute = ApiKeywordsIndexRouteImport.update({
  id: '/api/keywords/',
  path: '/api/keywords/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsIndexRoute = ApiCampaignsIndexRouteImport.update({
  id: '/api/campaigns/',
  path: '/api/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIndexRoute = ApiBlogIndexRouteImport.update({
  id: '/api/blog/',
  path: '/api/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdTemplatesIndexRoute =
  WorkspaceIdTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const WorkspaceIdSettingsIndexRoute =
  WorkspaceIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdCampaignsIndexRoute =
  WorkspaceIdCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const ApiWorkspaceGenerateDescriptionRoute =
  ApiWorkspaceGenerateDescriptionRouteImport.update({
    id: '/api/workspace/generate-description',
    path: '/api/workspace/generate-description',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksEmailInboundRoute = ApiWebhooksEmailInboundRouteImport.update({
  id: '/api/webhooks/email-inbound',
  path: '/api/webhooks/email-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIdRoute = ApiTemplatesIdRouteImport.update({
  id: '/api/templates/$id',
  path: '/api/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubredditsIdRoute = ApiSubredditsIdRouteImport.update({
  id: '/api/subreddits/$id',
  path: '/api/subreddits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditToPipelineRoute = ApiRedditToPipelineRouteImport.update({
  id: '/api/reddit/to-pipeline',
  path: '/api/reddit/to-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditSuggestRoute = ApiRedditSuggestRouteImport.update({
  id: '/api/reddit/suggest',
  path: '/api/reddit/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditSearchRoute = ApiRedditSearchRouteImport.update({
  id: '/api/reddit/search',
  path: '/api/reddit/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditPostsRoute = ApiRedditPostsRouteImport.update({
  id: '/api/reddit/posts',
  path: '/api/reddit/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineLeadsRoute = ApiPipelineLeadsRouteImport.update({
  id: '/api/pipeline/leads',
  path: '/api/pipeline/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineImportRoute = ApiPipelineImportRouteImport.update({
  id: '/api/pipeline/import',
  path: '/api/pipeline/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineEnrichRoute = ApiPipelineEnrichRouteImport.update({
  id: '/api/pipeline/enrich',
  path: '/api/pipeline/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinSearchRoute = ApiLinkedinSearchRouteImport.update({
  id: '/api/linkedin/search',
  path: '/api/linkedin/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinGeneratePostRoute = ApiLinkedinGeneratePostRouteImport.update({
  id: '/api/linkedin/generate-post',
  path: '/api/linkedin/generate-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsGenerateRoute = ApiKeywordsGenerateRouteImport.update({
  id: '/api/keywords/generate',
  path: '/api/keywords/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsIdRoute = ApiKeywordsIdRouteImport.update({
  id: '/api/keywords/$id',
  path: '/api/keywords/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailTestSmtpRoute = ApiEmailTestSmtpRouteImport.update({
  id: '/api/email/test-smtp',
  path: '/api/email/test-smtp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSendRoute = ApiEmailSendRouteImport.update({
  id: '/api/email/send',
  path: '/api/email/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectoriesSearchRoute = ApiDirectoriesSearchRouteImport.update({
  id: '/api/directories/search',
  path: '/api/directories/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectoriesEnrichRoute = ApiDirectoriesEnrichRouteImport.update({
  id: '/api/directories/enrich',
  path: '/api/directories/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectoriesAddRoute = ApiDirectoriesAddRouteImport.update({
  id: '/api/directories/add',
  path: '/api/directories/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsSchedulerRoute = ApiCampaignsSchedulerRouteImport.update({
  id: '/api/campaigns/scheduler',
  path: '/api/campaigns/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsProcessDueDraftsRoute =
  ApiCampaignsProcessDueDraftsRouteImport.update({
    id: '/api/campaigns/process-due-drafts',
    path: '/api/campaigns/process-due-drafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCampaignsIdRoute = ApiCampaignsIdRouteImport.update({
  id: '/api/campaigns/$id',
  path: '/api/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogGenerateRoute = ApiBlogGenerateRouteImport.update({
  id: '/api/blog/generate',
  path: '/api/blog/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIdRoute = ApiBlogIdRouteImport.update({
  id: '/api/blog/$id',
  path: '/api/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRunRoute = ApiAgentRunRouteImport.update({
  id: '/api/agent/run',
  path: '/api/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdTemplatesNewRoute = WorkspaceIdTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdTemplatesTemplateIdRoute =
  WorkspaceIdTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const WorkspaceIdSettingsWorkspaceRoute =
  WorkspaceIdSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdSettingsProfileRoute =
  WorkspaceIdSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdSettingsEmailRoute =
  WorkspaceIdSettingsEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdSettingsDangerRoute =
  WorkspaceIdSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdSettingsBillingRoute =
  WorkspaceIdSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdSettingsAppearanceRoute =
  WorkspaceIdSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdSettingsAgentRoute =
  WorkspaceIdSettingsAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdCampaignsNewRoute = WorkspaceIdCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdCampaignsIdIndexRoute =
  WorkspaceIdCampaignsIdIndexRouteImport.update({
    id: '/campaigns/$id/',
    path: '/campaigns/$id/',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const ApiRedditPostsIdRoute = ApiRedditPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRedditPostsRoute,
} as any)
const ApiPipelineLeadsIdRoute = ApiPipelineLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPipelineLeadsRoute,
} as any)
const ApiCampaignsIdStepsRoute = ApiCampaignsIdStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => ApiCampaignsIdRoute,
} as any)
const ApiCampaignsIdRunRoute = ApiCampaignsIdRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => ApiCampaignsIdRoute,
} as any)
const ApiCampaignsIdLeadsRoute = ApiCampaignsIdLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ApiCampaignsIdRoute,
} as any)
const ApiCampaignsIdGenerateDraftsRoute =
  ApiCampaignsIdGenerateDraftsRouteImport.update({
    id: '/generate-drafts',
    path: '/generate-drafts',
    getParentRoute: () => ApiCampaignsIdRoute,
  } as any)
const ApiCampaignsIdDraftsRoute = ApiCampaignsIdDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => ApiCampaignsIdRoute,
} as any)
const ApiCampaignsIdStepsStepIdRoute =
  ApiCampaignsIdStepsStepIdRouteImport.update({
    id: '/$stepId',
    path: '/$stepId',
    getParentRoute: () => ApiCampaignsIdStepsRoute,
  } as any)
const ApiCampaignsIdDraftsDraftIdRoute =
  ApiCampaignsIdDraftsDraftIdRouteImport.update({
    id: '/$draftId',
    path: '/$draftId',
    getParentRoute: () => ApiCampaignsIdDraftsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRouteRouteWithChildren
  '/$workspaceId/agent': typeof WorkspaceIdAgentRoute
  '/$workspaceId/analytics': typeof WorkspaceIdAnalyticsRoute
  '/$workspaceId/blog': typeof WorkspaceIdBlogRoute
  '/$workspaceId/directories': typeof WorkspaceIdDirectoriesRoute
  '/$workspaceId/keywords': typeof WorkspaceIdKeywordsRoute
  '/$workspaceId/linkedin': typeof WorkspaceIdLinkedinRoute
  '/$workspaceId/linkedin-posts': typeof WorkspaceIdLinkedinPostsRoute
  '/$workspaceId/pipeline': typeof WorkspaceIdPipelineRoute
  '/$workspaceId/reddit': typeof WorkspaceIdRedditRoute
  '/$workspaceId/': typeof WorkspaceIdIndexRoute
  '/$workspaceId/campaigns/new': typeof WorkspaceIdCampaignsNewRoute
  '/$workspaceId/settings/agent': typeof WorkspaceIdSettingsAgentRoute
  '/$workspaceId/settings/appearance': typeof WorkspaceIdSettingsAppearanceRoute
  '/$workspaceId/settings/billing': typeof WorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/danger': typeof WorkspaceIdSettingsDangerRoute
  '/$workspaceId/settings/email': typeof WorkspaceIdSettingsEmailRoute
  '/$workspaceId/settings/profile': typeof WorkspaceIdSettingsProfileRoute
  '/$workspaceId/settings/workspace': typeof WorkspaceIdSettingsWorkspaceRoute
  '/$workspaceId/templates/$templateId': typeof WorkspaceIdTemplatesTemplateIdRoute
  '/$workspaceId/templates/new': typeof WorkspaceIdTemplatesNewRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/generate': typeof ApiBlogGenerateRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRouteWithChildren
  '/api/campaigns/process-due-drafts': typeof ApiCampaignsProcessDueDraftsRoute
  '/api/campaigns/scheduler': typeof ApiCampaignsSchedulerRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/directories/add': typeof ApiDirectoriesAddRoute
  '/api/directories/enrich': typeof ApiDirectoriesEnrichRoute
  '/api/directories/search': typeof ApiDirectoriesSearchRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/email/test-smtp': typeof ApiEmailTestSmtpRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRoute
  '/api/keywords/generate': typeof ApiKeywordsGenerateRoute
  '/api/linkedin/generate-post': typeof ApiLinkedinGeneratePostRoute
  '/api/linkedin/search': typeof ApiLinkedinSearchRoute
  '/api/pipeline/enrich': typeof ApiPipelineEnrichRoute
  '/api/pipeline/import': typeof ApiPipelineImportRoute
  '/api/pipeline/leads': typeof ApiPipelineLeadsRouteWithChildren
  '/api/reddit/posts': typeof ApiRedditPostsRouteWithChildren
  '/api/reddit/search': typeof ApiRedditSearchRoute
  '/api/reddit/suggest': typeof ApiRedditSuggestRoute
  '/api/reddit/to-pipeline': typeof ApiRedditToPipelineRoute
  '/api/subreddits/$id': typeof ApiSubredditsIdRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/api/webhooks/email-inbound': typeof ApiWebhooksEmailInboundRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/workspace/generate-description': typeof ApiWorkspaceGenerateDescriptionRoute
  '/$workspaceId/campaigns/': typeof WorkspaceIdCampaignsIndexRoute
  '/$workspaceId/settings/': typeof WorkspaceIdSettingsIndexRoute
  '/$workspaceId/templates/': typeof WorkspaceIdTemplatesIndexRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/campaigns/': typeof ApiCampaignsIndexRoute
  '/api/keywords/': typeof ApiKeywordsIndexRoute
  '/api/pipeline/': typeof ApiPipelineIndexRoute
  '/api/subreddits/': typeof ApiSubredditsIndexRoute
  '/api/templates/': typeof ApiTemplatesIndexRoute
  '/api/campaigns/$id/drafts': typeof ApiCampaignsIdDraftsRouteWithChildren
  '/api/campaigns/$id/generate-drafts': typeof ApiCampaignsIdGenerateDraftsRoute
  '/api/campaigns/$id/leads': typeof ApiCampaignsIdLeadsRoute
  '/api/campaigns/$id/run': typeof ApiCampaignsIdRunRoute
  '/api/campaigns/$id/steps': typeof ApiCampaignsIdStepsRouteWithChildren
  '/api/pipeline/leads/$id': typeof ApiPipelineLeadsIdRoute
  '/api/reddit/posts/$id': typeof ApiRedditPostsIdRoute
  '/$workspaceId/campaigns/$id/': typeof WorkspaceIdCampaignsIdIndexRoute
  '/api/campaigns/$id/drafts/$draftId': typeof ApiCampaignsIdDraftsDraftIdRoute
  '/api/campaigns/$id/steps/$stepId': typeof ApiCampaignsIdStepsStepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$workspaceId/agent': typeof WorkspaceIdAgentRoute
  '/$workspaceId/analytics': typeof WorkspaceIdAnalyticsRoute
  '/$workspaceId/blog': typeof WorkspaceIdBlogRoute
  '/$workspaceId/directories': typeof WorkspaceIdDirectoriesRoute
  '/$workspaceId/keywords': typeof WorkspaceIdKeywordsRoute
  '/$workspaceId/linkedin': typeof WorkspaceIdLinkedinRoute
  '/$workspaceId/linkedin-posts': typeof WorkspaceIdLinkedinPostsRoute
  '/$workspaceId/pipeline': typeof WorkspaceIdPipelineRoute
  '/$workspaceId/reddit': typeof WorkspaceIdRedditRoute
  '/$workspaceId': typeof WorkspaceIdIndexRoute
  '/$workspaceId/campaigns/new': typeof WorkspaceIdCampaignsNewRoute
  '/$workspaceId/settings/agent': typeof WorkspaceIdSettingsAgentRoute
  '/$workspaceId/settings/appearance': typeof WorkspaceIdSettingsAppearanceRoute
  '/$workspaceId/settings/billing': typeof WorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/danger': typeof WorkspaceIdSettingsDangerRoute
  '/$workspaceId/settings/email': typeof WorkspaceIdSettingsEmailRoute
  '/$workspaceId/settings/profile': typeof WorkspaceIdSettingsProfileRoute
  '/$workspaceId/settings/workspace': typeof WorkspaceIdSettingsWorkspaceRoute
  '/$workspaceId/templates/$templateId': typeof WorkspaceIdTemplatesTemplateIdRoute
  '/$workspaceId/templates/new': typeof WorkspaceIdTemplatesNewRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/generate': typeof ApiBlogGenerateRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRouteWithChildren
  '/api/campaigns/process-due-drafts': typeof ApiCampaignsProcessDueDraftsRoute
  '/api/campaigns/scheduler': typeof ApiCampaignsSchedulerRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/directories/add': typeof ApiDirectoriesAddRoute
  '/api/directories/enrich': typeof ApiDirectoriesEnrichRoute
  '/api/directories/search': typeof ApiDirectoriesSearchRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/email/test-smtp': typeof ApiEmailTestSmtpRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRoute
  '/api/keywords/generate': typeof ApiKeywordsGenerateRoute
  '/api/linkedin/generate-post': typeof ApiLinkedinGeneratePostRoute
  '/api/linkedin/search': typeof ApiLinkedinSearchRoute
  '/api/pipeline/enrich': typeof ApiPipelineEnrichRoute
  '/api/pipeline/import': typeof ApiPipelineImportRoute
  '/api/pipeline/leads': typeof ApiPipelineLeadsRouteWithChildren
  '/api/reddit/posts': typeof ApiRedditPostsRouteWithChildren
  '/api/reddit/search': typeof ApiRedditSearchRoute
  '/api/reddit/suggest': typeof ApiRedditSuggestRoute
  '/api/reddit/to-pipeline': typeof ApiRedditToPipelineRoute
  '/api/subreddits/$id': typeof ApiSubredditsIdRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/api/webhooks/email-inbound': typeof ApiWebhooksEmailInboundRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/workspace/generate-description': typeof ApiWorkspaceGenerateDescriptionRoute
  '/$workspaceId/campaigns': typeof WorkspaceIdCampaignsIndexRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsIndexRoute
  '/$workspaceId/templates': typeof WorkspaceIdTemplatesIndexRoute
  '/api/blog': typeof ApiBlogIndexRoute
  '/api/campaigns': typeof ApiCampaignsIndexRoute
  '/api/keywords': typeof ApiKeywordsIndexRoute
  '/api/pipeline': typeof ApiPipelineIndexRoute
  '/api/subreddits': typeof ApiSubredditsIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/api/campaigns/$id/drafts': typeof ApiCampaignsIdDraftsRouteWithChildren
  '/api/campaigns/$id/generate-drafts': typeof ApiCampaignsIdGenerateDraftsRoute
  '/api/campaigns/$id/leads': typeof ApiCampaignsIdLeadsRoute
  '/api/campaigns/$id/run': typeof ApiCampaignsIdRunRoute
  '/api/campaigns/$id/steps': typeof ApiCampaignsIdStepsRouteWithChildren
  '/api/pipeline/leads/$id': typeof ApiPipelineLeadsIdRoute
  '/api/reddit/posts/$id': typeof ApiRedditPostsIdRoute
  '/$workspaceId/campaigns/$id': typeof WorkspaceIdCampaignsIdIndexRoute
  '/api/campaigns/$id/drafts/$draftId': typeof ApiCampaignsIdDraftsDraftIdRoute
  '/api/campaigns/$id/steps/$stepId': typeof ApiCampaignsIdStepsStepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRouteRouteWithChildren
  '/$workspaceId/agent': typeof WorkspaceIdAgentRoute
  '/$workspaceId/analytics': typeof WorkspaceIdAnalyticsRoute
  '/$workspaceId/blog': typeof WorkspaceIdBlogRoute
  '/$workspaceId/directories': typeof WorkspaceIdDirectoriesRoute
  '/$workspaceId/keywords': typeof WorkspaceIdKeywordsRoute
  '/$workspaceId/linkedin': typeof WorkspaceIdLinkedinRoute
  '/$workspaceId/linkedin-posts': typeof WorkspaceIdLinkedinPostsRoute
  '/$workspaceId/pipeline': typeof WorkspaceIdPipelineRoute
  '/$workspaceId/reddit': typeof WorkspaceIdRedditRoute
  '/$workspaceId/': typeof WorkspaceIdIndexRoute
  '/$workspaceId/campaigns/new': typeof WorkspaceIdCampaignsNewRoute
  '/$workspaceId/settings/agent': typeof WorkspaceIdSettingsAgentRoute
  '/$workspaceId/settings/appearance': typeof WorkspaceIdSettingsAppearanceRoute
  '/$workspaceId/settings/billing': typeof WorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/danger': typeof WorkspaceIdSettingsDangerRoute
  '/$workspaceId/settings/email': typeof WorkspaceIdSettingsEmailRoute
  '/$workspaceId/settings/profile': typeof WorkspaceIdSettingsProfileRoute
  '/$workspaceId/settings/workspace': typeof WorkspaceIdSettingsWorkspaceRoute
  '/$workspaceId/templates/$templateId': typeof WorkspaceIdTemplatesTemplateIdRoute
  '/$workspaceId/templates/new': typeof WorkspaceIdTemplatesNewRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/generate': typeof ApiBlogGenerateRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRouteWithChildren
  '/api/campaigns/process-due-drafts': typeof ApiCampaignsProcessDueDraftsRoute
  '/api/campaigns/scheduler': typeof ApiCampaignsSchedulerRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/directories/add': typeof ApiDirectoriesAddRoute
  '/api/directories/enrich': typeof ApiDirectoriesEnrichRoute
  '/api/directories/search': typeof ApiDirectoriesSearchRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/email/test-smtp': typeof ApiEmailTestSmtpRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRoute
  '/api/keywords/generate': typeof ApiKeywordsGenerateRoute
  '/api/linkedin/generate-post': typeof ApiLinkedinGeneratePostRoute
  '/api/linkedin/search': typeof ApiLinkedinSearchRoute
  '/api/pipeline/enrich': typeof ApiPipelineEnrichRoute
  '/api/pipeline/import': typeof ApiPipelineImportRoute
  '/api/pipeline/leads': typeof ApiPipelineLeadsRouteWithChildren
  '/api/reddit/posts': typeof ApiRedditPostsRouteWithChildren
  '/api/reddit/search': typeof ApiRedditSearchRoute
  '/api/reddit/suggest': typeof ApiRedditSuggestRoute
  '/api/reddit/to-pipeline': typeof ApiRedditToPipelineRoute
  '/api/subreddits/$id': typeof ApiSubredditsIdRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/api/webhooks/email-inbound': typeof ApiWebhooksEmailInboundRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/workspace/generate-description': typeof ApiWorkspaceGenerateDescriptionRoute
  '/$workspaceId/campaigns/': typeof WorkspaceIdCampaignsIndexRoute
  '/$workspaceId/settings/': typeof WorkspaceIdSettingsIndexRoute
  '/$workspaceId/templates/': typeof WorkspaceIdTemplatesIndexRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/campaigns/': typeof ApiCampaignsIndexRoute
  '/api/keywords/': typeof ApiKeywordsIndexRoute
  '/api/pipeline/': typeof ApiPipelineIndexRoute
  '/api/subreddits/': typeof ApiSubredditsIndexRoute
  '/api/templates/': typeof ApiTemplatesIndexRoute
  '/api/campaigns/$id/drafts': typeof ApiCampaignsIdDraftsRouteWithChildren
  '/api/campaigns/$id/generate-drafts': typeof ApiCampaignsIdGenerateDraftsRoute
  '/api/campaigns/$id/leads': typeof ApiCampaignsIdLeadsRoute
  '/api/campaigns/$id/run': typeof ApiCampaignsIdRunRoute
  '/api/campaigns/$id/steps': typeof ApiCampaignsIdStepsRouteWithChildren
  '/api/pipeline/leads/$id': typeof ApiPipelineLeadsIdRoute
  '/api/reddit/posts/$id': typeof ApiRedditPostsIdRoute
  '/$workspaceId/campaigns/$id/': typeof WorkspaceIdCampaignsIdIndexRoute
  '/api/campaigns/$id/drafts/$draftId': typeof ApiCampaignsIdDraftsDraftIdRoute
  '/api/campaigns/$id/steps/$stepId': typeof ApiCampaignsIdStepsStepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceId'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/$workspaceId/settings'
    | '/$workspaceId/agent'
    | '/$workspaceId/analytics'
    | '/$workspaceId/blog'
    | '/$workspaceId/directories'
    | '/$workspaceId/keywords'
    | '/$workspaceId/linkedin'
    | '/$workspaceId/linkedin-posts'
    | '/$workspaceId/pipeline'
    | '/$workspaceId/reddit'
    | '/$workspaceId/'
    | '/$workspaceId/campaigns/new'
    | '/$workspaceId/settings/agent'
    | '/$workspaceId/settings/appearance'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/danger'
    | '/$workspaceId/settings/email'
    | '/$workspaceId/settings/profile'
    | '/$workspaceId/settings/workspace'
    | '/$workspaceId/templates/$templateId'
    | '/$workspaceId/templates/new'
    | '/api/agent/run'
    | '/api/auth/$'
    | '/api/blog/$id'
    | '/api/blog/generate'
    | '/api/campaigns/$id'
    | '/api/campaigns/process-due-drafts'
    | '/api/campaigns/scheduler'
    | '/api/dashboard/stats'
    | '/api/directories/add'
    | '/api/directories/enrich'
    | '/api/directories/search'
    | '/api/email/send'
    | '/api/email/test-smtp'
    | '/api/keywords/$id'
    | '/api/keywords/generate'
    | '/api/linkedin/generate-post'
    | '/api/linkedin/search'
    | '/api/pipeline/enrich'
    | '/api/pipeline/import'
    | '/api/pipeline/leads'
    | '/api/reddit/posts'
    | '/api/reddit/search'
    | '/api/reddit/suggest'
    | '/api/reddit/to-pipeline'
    | '/api/subreddits/$id'
    | '/api/templates/$id'
    | '/api/webhooks/email-inbound'
    | '/api/webhooks/resend'
    | '/api/workspace/generate-description'
    | '/$workspaceId/campaigns/'
    | '/$workspaceId/settings/'
    | '/$workspaceId/templates/'
    | '/api/blog/'
    | '/api/campaigns/'
    | '/api/keywords/'
    | '/api/pipeline/'
    | '/api/subreddits/'
    | '/api/templates/'
    | '/api/campaigns/$id/drafts'
    | '/api/campaigns/$id/generate-drafts'
    | '/api/campaigns/$id/leads'
    | '/api/campaigns/$id/run'
    | '/api/campaigns/$id/steps'
    | '/api/pipeline/leads/$id'
    | '/api/reddit/posts/$id'
    | '/$workspaceId/campaigns/$id/'
    | '/api/campaigns/$id/drafts/$draftId'
    | '/api/campaigns/$id/steps/$stepId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/$workspaceId/agent'
    | '/$workspaceId/analytics'
    | '/$workspaceId/blog'
    | '/$workspaceId/directories'
    | '/$workspaceId/keywords'
    | '/$workspaceId/linkedin'
    | '/$workspaceId/linkedin-posts'
    | '/$workspaceId/pipeline'
    | '/$workspaceId/reddit'
    | '/$workspaceId'
    | '/$workspaceId/campaigns/new'
    | '/$workspaceId/settings/agent'
    | '/$workspaceId/settings/appearance'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/danger'
    | '/$workspaceId/settings/email'
    | '/$workspaceId/settings/profile'
    | '/$workspaceId/settings/workspace'
    | '/$workspaceId/templates/$templateId'
    | '/$workspaceId/templates/new'
    | '/api/agent/run'
    | '/api/auth/$'
    | '/api/blog/$id'
    | '/api/blog/generate'
    | '/api/campaigns/$id'
    | '/api/campaigns/process-due-drafts'
    | '/api/campaigns/scheduler'
    | '/api/dashboard/stats'
    | '/api/directories/add'
    | '/api/directories/enrich'
    | '/api/directories/search'
    | '/api/email/send'
    | '/api/email/test-smtp'
    | '/api/keywords/$id'
    | '/api/keywords/generate'
    | '/api/linkedin/generate-post'
    | '/api/linkedin/search'
    | '/api/pipeline/enrich'
    | '/api/pipeline/import'
    | '/api/pipeline/leads'
    | '/api/reddit/posts'
    | '/api/reddit/search'
    | '/api/reddit/suggest'
    | '/api/reddit/to-pipeline'
    | '/api/subreddits/$id'
    | '/api/templates/$id'
    | '/api/webhooks/email-inbound'
    | '/api/webhooks/resend'
    | '/api/workspace/generate-description'
    | '/$workspaceId/campaigns'
    | '/$workspaceId/settings'
    | '/$workspaceId/templates'
    | '/api/blog'
    | '/api/campaigns'
    | '/api/keywords'
    | '/api/pipeline'
    | '/api/subreddits'
    | '/api/templates'
    | '/api/campaigns/$id/drafts'
    | '/api/campaigns/$id/generate-drafts'
    | '/api/campaigns/$id/leads'
    | '/api/campaigns/$id/run'
    | '/api/campaigns/$id/steps'
    | '/api/pipeline/leads/$id'
    | '/api/reddit/posts/$id'
    | '/$workspaceId/campaigns/$id'
    | '/api/campaigns/$id/drafts/$draftId'
    | '/api/campaigns/$id/steps/$stepId'
  id:
    | '__root__'
    | '/'
    | '/$workspaceId'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/$workspaceId/settings'
    | '/$workspaceId/agent'
    | '/$workspaceId/analytics'
    | '/$workspaceId/blog'
    | '/$workspaceId/directories'
    | '/$workspaceId/keywords'
    | '/$workspaceId/linkedin'
    | '/$workspaceId/linkedin-posts'
    | '/$workspaceId/pipeline'
    | '/$workspaceId/reddit'
    | '/$workspaceId/'
    | '/$workspaceId/campaigns/new'
    | '/$workspaceId/settings/agent'
    | '/$workspaceId/settings/appearance'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/danger'
    | '/$workspaceId/settings/email'
    | '/$workspaceId/settings/profile'
    | '/$workspaceId/settings/workspace'
    | '/$workspaceId/templates/$templateId'
    | '/$workspaceId/templates/new'
    | '/api/agent/run'
    | '/api/auth/$'
    | '/api/blog/$id'
    | '/api/blog/generate'
    | '/api/campaigns/$id'
    | '/api/campaigns/process-due-drafts'
    | '/api/campaigns/scheduler'
    | '/api/dashboard/stats'
    | '/api/directories/add'
    | '/api/directories/enrich'
    | '/api/directories/search'
    | '/api/email/send'
    | '/api/email/test-smtp'
    | '/api/keywords/$id'
    | '/api/keywords/generate'
    | '/api/linkedin/generate-post'
    | '/api/linkedin/search'
    | '/api/pipeline/enrich'
    | '/api/pipeline/import'
    | '/api/pipeline/leads'
    | '/api/reddit/posts'
    | '/api/reddit/search'
    | '/api/reddit/suggest'
    | '/api/reddit/to-pipeline'
    | '/api/subreddits/$id'
    | '/api/templates/$id'
    | '/api/webhooks/email-inbound'
    | '/api/webhooks/resend'
    | '/api/workspace/generate-description'
    | '/$workspaceId/campaigns/'
    | '/$workspaceId/settings/'
    | '/$workspaceId/templates/'
    | '/api/blog/'
    | '/api/campaigns/'
    | '/api/keywords/'
    | '/api/pipeline/'
    | '/api/subreddits/'
    | '/api/templates/'
    | '/api/campaigns/$id/drafts'
    | '/api/campaigns/$id/generate-drafts'
    | '/api/campaigns/$id/leads'
    | '/api/campaigns/$id/run'
    | '/api/campaigns/$id/steps'
    | '/api/pipeline/leads/$id'
    | '/api/reddit/posts/$id'
    | '/$workspaceId/campaigns/$id/'
    | '/api/campaigns/$id/drafts/$draftId'
    | '/api/campaigns/$id/steps/$stepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceIdRouteRoute: typeof WorkspaceIdRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAgentRunRoute: typeof ApiAgentRunRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlogIdRoute: typeof ApiBlogIdRoute
  ApiBlogGenerateRoute: typeof ApiBlogGenerateRoute
  ApiCampaignsIdRoute: typeof ApiCampaignsIdRouteWithChildren
  ApiCampaignsProcessDueDraftsRoute: typeof ApiCampaignsProcessDueDraftsRoute
  ApiCampaignsSchedulerRoute: typeof ApiCampaignsSchedulerRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiDirectoriesAddRoute: typeof ApiDirectoriesAddRoute
  ApiDirectoriesEnrichRoute: typeof ApiDirectoriesEnrichRoute
  ApiDirectoriesSearchRoute: typeof ApiDirectoriesSearchRoute
  ApiEmailSendRoute: typeof ApiEmailSendRoute
  ApiEmailTestSmtpRoute: typeof ApiEmailTestSmtpRoute
  ApiKeywordsIdRoute: typeof ApiKeywordsIdRoute
  ApiKeywordsGenerateRoute: typeof ApiKeywordsGenerateRoute
  ApiLinkedinGeneratePostRoute: typeof ApiLinkedinGeneratePostRoute
  ApiLinkedinSearchRoute: typeof ApiLinkedinSearchRoute
  ApiPipelineEnrichRoute: typeof ApiPipelineEnrichRoute
  ApiPipelineImportRoute: typeof ApiPipelineImportRoute
  ApiPipelineLeadsRoute: typeof ApiPipelineLeadsRouteWithChildren
  ApiRedditPostsRoute: typeof ApiRedditPostsRouteWithChildren
  ApiRedditSearchRoute: typeof ApiRedditSearchRoute
  ApiRedditSuggestRoute: typeof ApiRedditSuggestRoute
  ApiRedditToPipelineRoute: typeof ApiRedditToPipelineRoute
  ApiSubredditsIdRoute: typeof ApiSubredditsIdRoute
  ApiTemplatesIdRoute: typeof ApiTemplatesIdRoute
  ApiWebhooksEmailInboundRoute: typeof ApiWebhooksEmailInboundRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
  ApiWorkspaceGenerateDescriptionRoute: typeof ApiWorkspaceGenerateDescriptionRoute
  ApiBlogIndexRoute: typeof ApiBlogIndexRoute
  ApiCampaignsIndexRoute: typeof ApiCampaignsIndexRoute
  ApiKeywordsIndexRoute: typeof ApiKeywordsIndexRoute
  ApiPipelineIndexRoute: typeof ApiPipelineIndexRoute
  ApiSubredditsIndexRoute: typeof ApiSubredditsIndexRoute
  ApiTemplatesIndexRoute: typeof ApiTemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId': {
      id: '/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof WorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/': {
      id: '/$workspaceId/'
      path: '/'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof WorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/reddit': {
      id: '/$workspaceId/reddit'
      path: '/reddit'
      fullPath: '/$workspaceId/reddit'
      preLoaderRoute: typeof WorkspaceIdRedditRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/pipeline': {
      id: '/$workspaceId/pipeline'
      path: '/pipeline'
      fullPath: '/$workspaceId/pipeline'
      preLoaderRoute: typeof WorkspaceIdPipelineRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/linkedin-posts': {
      id: '/$workspaceId/linkedin-posts'
      path: '/linkedin-posts'
      fullPath: '/$workspaceId/linkedin-posts'
      preLoaderRoute: typeof WorkspaceIdLinkedinPostsRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/linkedin': {
      id: '/$workspaceId/linkedin'
      path: '/linkedin'
      fullPath: '/$workspaceId/linkedin'
      preLoaderRoute: typeof WorkspaceIdLinkedinRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/keywords': {
      id: '/$workspaceId/keywords'
      path: '/keywords'
      fullPath: '/$workspaceId/keywords'
      preLoaderRoute: typeof WorkspaceIdKeywordsRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/directories': {
      id: '/$workspaceId/directories'
      path: '/directories'
      fullPath: '/$workspaceId/directories'
      preLoaderRoute: typeof WorkspaceIdDirectoriesRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/blog': {
      id: '/$workspaceId/blog'
      path: '/blog'
      fullPath: '/$workspaceId/blog'
      preLoaderRoute: typeof WorkspaceIdBlogRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/analytics': {
      id: '/$workspaceId/analytics'
      path: '/analytics'
      fullPath: '/$workspaceId/analytics'
      preLoaderRoute: typeof WorkspaceIdAnalyticsRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/agent': {
      id: '/$workspaceId/agent'
      path: '/agent'
      fullPath: '/$workspaceId/agent'
      preLoaderRoute: typeof WorkspaceIdAgentRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/settings': {
      id: '/$workspaceId/settings'
      path: '/settings'
      fullPath: '/$workspaceId/settings'
      preLoaderRoute: typeof WorkspaceIdSettingsRouteRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/api/templates/': {
      id: '/api/templates/'
      path: '/api/templates'
      fullPath: '/api/templates/'
      preLoaderRoute: typeof ApiTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subreddits/': {
      id: '/api/subreddits/'
      path: '/api/subreddits'
      fullPath: '/api/subreddits/'
      preLoaderRoute: typeof ApiSubredditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/': {
      id: '/api/pipeline/'
      path: '/api/pipeline'
      fullPath: '/api/pipeline/'
      preLoaderRoute: typeof ApiPipelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords/': {
      id: '/api/keywords/'
      path: '/api/keywords'
      fullPath: '/api/keywords/'
      preLoaderRoute: typeof ApiKeywordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/': {
      id: '/api/campaigns/'
      path: '/api/campaigns'
      fullPath: '/api/campaigns/'
      preLoaderRoute: typeof ApiCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/': {
      id: '/api/blog/'
      path: '/api/blog'
      fullPath: '/api/blog/'
      preLoaderRoute: typeof ApiBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/templates/': {
      id: '/$workspaceId/templates/'
      path: '/templates'
      fullPath: '/$workspaceId/templates/'
      preLoaderRoute: typeof WorkspaceIdTemplatesIndexRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/settings/': {
      id: '/$workspaceId/settings/'
      path: '/'
      fullPath: '/$workspaceId/settings/'
      preLoaderRoute: typeof WorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/campaigns/': {
      id: '/$workspaceId/campaigns/'
      path: '/campaigns'
      fullPath: '/$workspaceId/campaigns/'
      preLoaderRoute: typeof WorkspaceIdCampaignsIndexRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/api/workspace/generate-description': {
      id: '/api/workspace/generate-description'
      path: '/api/workspace/generate-description'
      fullPath: '/api/workspace/generate-description'
      preLoaderRoute: typeof ApiWorkspaceGenerateDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/email-inbound': {
      id: '/api/webhooks/email-inbound'
      path: '/api/webhooks/email-inbound'
      fullPath: '/api/webhooks/email-inbound'
      preLoaderRoute: typeof ApiWebhooksEmailInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/$id': {
      id: '/api/templates/$id'
      path: '/api/templates/$id'
      fullPath: '/api/templates/$id'
      preLoaderRoute: typeof ApiTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subreddits/$id': {
      id: '/api/subreddits/$id'
      path: '/api/subreddits/$id'
      fullPath: '/api/subreddits/$id'
      preLoaderRoute: typeof ApiSubredditsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/to-pipeline': {
      id: '/api/reddit/to-pipeline'
      path: '/api/reddit/to-pipeline'
      fullPath: '/api/reddit/to-pipeline'
      preLoaderRoute: typeof ApiRedditToPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/suggest': {
      id: '/api/reddit/suggest'
      path: '/api/reddit/suggest'
      fullPath: '/api/reddit/suggest'
      preLoaderRoute: typeof ApiRedditSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/search': {
      id: '/api/reddit/search'
      path: '/api/reddit/search'
      fullPath: '/api/reddit/search'
      preLoaderRoute: typeof ApiRedditSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/posts': {
      id: '/api/reddit/posts'
      path: '/api/reddit/posts'
      fullPath: '/api/reddit/posts'
      preLoaderRoute: typeof ApiRedditPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/leads': {
      id: '/api/pipeline/leads'
      path: '/api/pipeline/leads'
      fullPath: '/api/pipeline/leads'
      preLoaderRoute: typeof ApiPipelineLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/import': {
      id: '/api/pipeline/import'
      path: '/api/pipeline/import'
      fullPath: '/api/pipeline/import'
      preLoaderRoute: typeof ApiPipelineImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/enrich': {
      id: '/api/pipeline/enrich'
      path: '/api/pipeline/enrich'
      fullPath: '/api/pipeline/enrich'
      preLoaderRoute: typeof ApiPipelineEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/search': {
      id: '/api/linkedin/search'
      path: '/api/linkedin/search'
      fullPath: '/api/linkedin/search'
      preLoaderRoute: typeof ApiLinkedinSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/generate-post': {
      id: '/api/linkedin/generate-post'
      path: '/api/linkedin/generate-post'
      fullPath: '/api/linkedin/generate-post'
      preLoaderRoute: typeof ApiLinkedinGeneratePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords/generate': {
      id: '/api/keywords/generate'
      path: '/api/keywords/generate'
      fullPath: '/api/keywords/generate'
      preLoaderRoute: typeof ApiKeywordsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords/$id': {
      id: '/api/keywords/$id'
      path: '/api/keywords/$id'
      fullPath: '/api/keywords/$id'
      preLoaderRoute: typeof ApiKeywordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/test-smtp': {
      id: '/api/email/test-smtp'
      path: '/api/email/test-smtp'
      fullPath: '/api/email/test-smtp'
      preLoaderRoute: typeof ApiEmailTestSmtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/send': {
      id: '/api/email/send'
      path: '/api/email/send'
      fullPath: '/api/email/send'
      preLoaderRoute: typeof ApiEmailSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/directories/search': {
      id: '/api/directories/search'
      path: '/api/directories/search'
      fullPath: '/api/directories/search'
      preLoaderRoute: typeof ApiDirectoriesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/directories/enrich': {
      id: '/api/directories/enrich'
      path: '/api/directories/enrich'
      fullPath: '/api/directories/enrich'
      preLoaderRoute: typeof ApiDirectoriesEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/directories/add': {
      id: '/api/directories/add'
      path: '/api/directories/add'
      fullPath: '/api/directories/add'
      preLoaderRoute: typeof ApiDirectoriesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/scheduler': {
      id: '/api/campaigns/scheduler'
      path: '/api/campaigns/scheduler'
      fullPath: '/api/campaigns/scheduler'
      preLoaderRoute: typeof ApiCampaignsSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/process-due-drafts': {
      id: '/api/campaigns/process-due-drafts'
      path: '/api/campaigns/process-due-drafts'
      fullPath: '/api/campaigns/process-due-drafts'
      preLoaderRoute: typeof ApiCampaignsProcessDueDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/$id': {
      id: '/api/campaigns/$id'
      path: '/api/campaigns/$id'
      fullPath: '/api/campaigns/$id'
      preLoaderRoute: typeof ApiCampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/generate': {
      id: '/api/blog/generate'
      path: '/api/blog/generate'
      fullPath: '/api/blog/generate'
      preLoaderRoute: typeof ApiBlogGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$id': {
      id: '/api/blog/$id'
      path: '/api/blog/$id'
      fullPath: '/api/blog/$id'
      preLoaderRoute: typeof ApiBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/run': {
      id: '/api/agent/run'
      path: '/api/agent/run'
      fullPath: '/api/agent/run'
      preLoaderRoute: typeof ApiAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/templates/new': {
      id: '/$workspaceId/templates/new'
      path: '/templates/new'
      fullPath: '/$workspaceId/templates/new'
      preLoaderRoute: typeof WorkspaceIdTemplatesNewRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/templates/$templateId': {
      id: '/$workspaceId/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/$workspaceId/templates/$templateId'
      preLoaderRoute: typeof WorkspaceIdTemplatesTemplateIdRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/settings/workspace': {
      id: '/$workspaceId/settings/workspace'
      path: '/workspace'
      fullPath: '/$workspaceId/settings/workspace'
      preLoaderRoute: typeof WorkspaceIdSettingsWorkspaceRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/settings/profile': {
      id: '/$workspaceId/settings/profile'
      path: '/profile'
      fullPath: '/$workspaceId/settings/profile'
      preLoaderRoute: typeof WorkspaceIdSettingsProfileRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/settings/email': {
      id: '/$workspaceId/settings/email'
      path: '/email'
      fullPath: '/$workspaceId/settings/email'
      preLoaderRoute: typeof WorkspaceIdSettingsEmailRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/settings/danger': {
      id: '/$workspaceId/settings/danger'
      path: '/danger'
      fullPath: '/$workspaceId/settings/danger'
      preLoaderRoute: typeof WorkspaceIdSettingsDangerRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/settings/billing': {
      id: '/$workspaceId/settings/billing'
      path: '/billing'
      fullPath: '/$workspaceId/settings/billing'
      preLoaderRoute: typeof WorkspaceIdSettingsBillingRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/settings/appearance': {
      id: '/$workspaceId/settings/appearance'
      path: '/appearance'
      fullPath: '/$workspaceId/settings/appearance'
      preLoaderRoute: typeof WorkspaceIdSettingsAppearanceRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/settings/agent': {
      id: '/$workspaceId/settings/agent'
      path: '/agent'
      fullPath: '/$workspaceId/settings/agent'
      preLoaderRoute: typeof WorkspaceIdSettingsAgentRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/campaigns/new': {
      id: '/$workspaceId/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/$workspaceId/campaigns/new'
      preLoaderRoute: typeof WorkspaceIdCampaignsNewRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/campaigns/$id/': {
      id: '/$workspaceId/campaigns/$id/'
      path: '/campaigns/$id'
      fullPath: '/$workspaceId/campaigns/$id/'
      preLoaderRoute: typeof WorkspaceIdCampaignsIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/api/reddit/posts/$id': {
      id: '/api/reddit/posts/$id'
      path: '/$id'
      fullPath: '/api/reddit/posts/$id'
      preLoaderRoute: typeof ApiRedditPostsIdRouteImport
      parentRoute: typeof ApiRedditPostsRoute
    }
    '/api/pipeline/leads/$id': {
      id: '/api/pipeline/leads/$id'
      path: '/$id'
      fullPath: '/api/pipeline/leads/$id'
      preLoaderRoute: typeof ApiPipelineLeadsIdRouteImport
      parentRoute: typeof ApiPipelineLeadsRoute
    }
    '/api/campaigns/$id/steps': {
      id: '/api/campaigns/$id/steps'
      path: '/steps'
      fullPath: '/api/campaigns/$id/steps'
      preLoaderRoute: typeof ApiCampaignsIdStepsRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
    '/api/campaigns/$id/run': {
      id: '/api/campaigns/$id/run'
      path: '/run'
      fullPath: '/api/campaigns/$id/run'
      preLoaderRoute: typeof ApiCampaignsIdRunRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
    '/api/campaigns/$id/leads': {
      id: '/api/campaigns/$id/leads'
      path: '/leads'
      fullPath: '/api/campaigns/$id/leads'
      preLoaderRoute: typeof ApiCampaignsIdLeadsRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
    '/api/campaigns/$id/generate-drafts': {
      id: '/api/campaigns/$id/generate-drafts'
      path: '/generate-drafts'
      fullPath: '/api/campaigns/$id/generate-drafts'
      preLoaderRoute: typeof ApiCampaignsIdGenerateDraftsRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
    '/api/campaigns/$id/drafts': {
      id: '/api/campaigns/$id/drafts'
      path: '/drafts'
      fullPath: '/api/campaigns/$id/drafts'
      preLoaderRoute: typeof ApiCampaignsIdDraftsRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
    '/api/campaigns/$id/steps/$stepId': {
      id: '/api/campaigns/$id/steps/$stepId'
      path: '/$stepId'
      fullPath: '/api/campaigns/$id/steps/$stepId'
      preLoaderRoute: typeof ApiCampaignsIdStepsStepIdRouteImport
      parentRoute: typeof ApiCampaignsIdStepsRoute
    }
    '/api/campaigns/$id/drafts/$draftId': {
      id: '/api/campaigns/$id/drafts/$draftId'
      path: '/$draftId'
      fullPath: '/api/campaigns/$id/drafts/$draftId'
      preLoaderRoute: typeof ApiCampaignsIdDraftsDraftIdRouteImport
      parentRoute: typeof ApiCampaignsIdDraftsRoute
    }
  }
}

interface WorkspaceIdSettingsRouteRouteChildren {
  WorkspaceIdSettingsAgentRoute: typeof WorkspaceIdSettingsAgentRoute
  WorkspaceIdSettingsAppearanceRoute: typeof WorkspaceIdSettingsAppearanceRoute
  WorkspaceIdSettingsBillingRoute: typeof WorkspaceIdSettingsBillingRoute
  WorkspaceIdSettingsDangerRoute: typeof WorkspaceIdSettingsDangerRoute
  WorkspaceIdSettingsEmailRoute: typeof WorkspaceIdSettingsEmailRoute
  WorkspaceIdSettingsProfileRoute: typeof WorkspaceIdSettingsProfileRoute
  WorkspaceIdSettingsWorkspaceRoute: typeof WorkspaceIdSettingsWorkspaceRoute
  WorkspaceIdSettingsIndexRoute: typeof WorkspaceIdSettingsIndexRoute
}

const WorkspaceIdSettingsRouteRouteChildren: WorkspaceIdSettingsRouteRouteChildren =
  {
    WorkspaceIdSettingsAgentRoute: WorkspaceIdSettingsAgentRoute,
    WorkspaceIdSettingsAppearanceRoute: WorkspaceIdSettingsAppearanceRoute,
    WorkspaceIdSettingsBillingRoute: WorkspaceIdSettingsBillingRoute,
    WorkspaceIdSettingsDangerRoute: WorkspaceIdSettingsDangerRoute,
    WorkspaceIdSettingsEmailRoute: WorkspaceIdSettingsEmailRoute,
    WorkspaceIdSettingsProfileRoute: WorkspaceIdSettingsProfileRoute,
    WorkspaceIdSettingsWorkspaceRoute: WorkspaceIdSettingsWorkspaceRoute,
    WorkspaceIdSettingsIndexRoute: WorkspaceIdSettingsIndexRoute,
  }

const WorkspaceIdSettingsRouteRouteWithChildren =
  WorkspaceIdSettingsRouteRoute._addFileChildren(
    WorkspaceIdSettingsRouteRouteChildren,
  )

interface WorkspaceIdRouteRouteChildren {
  WorkspaceIdSettingsRouteRoute: typeof WorkspaceIdSettingsRouteRouteWithChildren
  WorkspaceIdAgentRoute: typeof WorkspaceIdAgentRoute
  WorkspaceIdAnalyticsRoute: typeof WorkspaceIdAnalyticsRoute
  WorkspaceIdBlogRoute: typeof WorkspaceIdBlogRoute
  WorkspaceIdDirectoriesRoute: typeof WorkspaceIdDirectoriesRoute
  WorkspaceIdKeywordsRoute: typeof WorkspaceIdKeywordsRoute
  WorkspaceIdLinkedinRoute: typeof WorkspaceIdLinkedinRoute
  WorkspaceIdLinkedinPostsRoute: typeof WorkspaceIdLinkedinPostsRoute
  WorkspaceIdPipelineRoute: typeof WorkspaceIdPipelineRoute
  WorkspaceIdRedditRoute: typeof WorkspaceIdRedditRoute
  WorkspaceIdIndexRoute: typeof WorkspaceIdIndexRoute
  WorkspaceIdCampaignsNewRoute: typeof WorkspaceIdCampaignsNewRoute
  WorkspaceIdTemplatesTemplateIdRoute: typeof WorkspaceIdTemplatesTemplateIdRoute
  WorkspaceIdTemplatesNewRoute: typeof WorkspaceIdTemplatesNewRoute
  WorkspaceIdCampaignsIndexRoute: typeof WorkspaceIdCampaignsIndexRoute
  WorkspaceIdTemplatesIndexRoute: typeof WorkspaceIdTemplatesIndexRoute
  WorkspaceIdCampaignsIdIndexRoute: typeof WorkspaceIdCampaignsIdIndexRoute
}

const WorkspaceIdRouteRouteChildren: WorkspaceIdRouteRouteChildren = {
  WorkspaceIdSettingsRouteRoute: WorkspaceIdSettingsRouteRouteWithChildren,
  WorkspaceIdAgentRoute: WorkspaceIdAgentRoute,
  WorkspaceIdAnalyticsRoute: WorkspaceIdAnalyticsRoute,
  WorkspaceIdBlogRoute: WorkspaceIdBlogRoute,
  WorkspaceIdDirectoriesRoute: WorkspaceIdDirectoriesRoute,
  WorkspaceIdKeywordsRoute: WorkspaceIdKeywordsRoute,
  WorkspaceIdLinkedinRoute: WorkspaceIdLinkedinRoute,
  WorkspaceIdLinkedinPostsRoute: WorkspaceIdLinkedinPostsRoute,
  WorkspaceIdPipelineRoute: WorkspaceIdPipelineRoute,
  WorkspaceIdRedditRoute: WorkspaceIdRedditRoute,
  WorkspaceIdIndexRoute: WorkspaceIdIndexRoute,
  WorkspaceIdCampaignsNewRoute: WorkspaceIdCampaignsNewRoute,
  WorkspaceIdTemplatesTemplateIdRoute: WorkspaceIdTemplatesTemplateIdRoute,
  WorkspaceIdTemplatesNewRoute: WorkspaceIdTemplatesNewRoute,
  WorkspaceIdCampaignsIndexRoute: WorkspaceIdCampaignsIndexRoute,
  WorkspaceIdTemplatesIndexRoute: WorkspaceIdTemplatesIndexRoute,
  WorkspaceIdCampaignsIdIndexRoute: WorkspaceIdCampaignsIdIndexRoute,
}

const WorkspaceIdRouteRouteWithChildren =
  WorkspaceIdRouteRoute._addFileChildren(WorkspaceIdRouteRouteChildren)

interface ApiCampaignsIdDraftsRouteChildren {
  ApiCampaignsIdDraftsDraftIdRoute: typeof ApiCampaignsIdDraftsDraftIdRoute
}

const ApiCampaignsIdDraftsRouteChildren: ApiCampaignsIdDraftsRouteChildren = {
  ApiCampaignsIdDraftsDraftIdRoute: ApiCampaignsIdDraftsDraftIdRoute,
}

const ApiCampaignsIdDraftsRouteWithChildren =
  ApiCampaignsIdDraftsRoute._addFileChildren(ApiCampaignsIdDraftsRouteChildren)

interface ApiCampaignsIdStepsRouteChildren {
  ApiCampaignsIdStepsStepIdRoute: typeof ApiCampaignsIdStepsStepIdRoute
}

const ApiCampaignsIdStepsRouteChildren: ApiCampaignsIdStepsRouteChildren = {
  ApiCampaignsIdStepsStepIdRoute: ApiCampaignsIdStepsStepIdRoute,
}

const ApiCampaignsIdStepsRouteWithChildren =
  ApiCampaignsIdStepsRoute._addFileChildren(ApiCampaignsIdStepsRouteChildren)

interface ApiCampaignsIdRouteChildren {
  ApiCampaignsIdDraftsRoute: typeof ApiCampaignsIdDraftsRouteWithChildren
  ApiCampaignsIdGenerateDraftsRoute: typeof ApiCampaignsIdGenerateDraftsRoute
  ApiCampaignsIdLeadsRoute: typeof ApiCampaignsIdLeadsRoute
  ApiCampaignsIdRunRoute: typeof ApiCampaignsIdRunRoute
  ApiCampaignsIdStepsRoute: typeof ApiCampaignsIdStepsRouteWithChildren
}

const ApiCampaignsIdRouteChildren: ApiCampaignsIdRouteChildren = {
  ApiCampaignsIdDraftsRoute: ApiCampaignsIdDraftsRouteWithChildren,
  ApiCampaignsIdGenerateDraftsRoute: ApiCampaignsIdGenerateDraftsRoute,
  ApiCampaignsIdLeadsRoute: ApiCampaignsIdLeadsRoute,
  ApiCampaignsIdRunRoute: ApiCampaignsIdRunRoute,
  ApiCampaignsIdStepsRoute: ApiCampaignsIdStepsRouteWithChildren,
}

const ApiCampaignsIdRouteWithChildren = ApiCampaignsIdRoute._addFileChildren(
  ApiCampaignsIdRouteChildren,
)

interface ApiPipelineLeadsRouteChildren {
  ApiPipelineLeadsIdRoute: typeof ApiPipelineLeadsIdRoute
}

const ApiPipelineLeadsRouteChildren: ApiPipelineLeadsRouteChildren = {
  ApiPipelineLeadsIdRoute: ApiPipelineLeadsIdRoute,
}

const ApiPipelineLeadsRouteWithChildren =
  ApiPipelineLeadsRoute._addFileChildren(ApiPipelineLeadsRouteChildren)

interface ApiRedditPostsRouteChildren {
  ApiRedditPostsIdRoute: typeof ApiRedditPostsIdRoute
}

const ApiRedditPostsRouteChildren: ApiRedditPostsRouteChildren = {
  ApiRedditPostsIdRoute: ApiRedditPostsIdRoute,
}

const ApiRedditPostsRouteWithChildren = ApiRedditPostsRoute._addFileChildren(
  ApiRedditPostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceIdRouteRoute: WorkspaceIdRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAgentRunRoute: ApiAgentRunRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlogIdRoute: ApiBlogIdRoute,
  ApiBlogGenerateRoute: ApiBlogGenerateRoute,
  ApiCampaignsIdRoute: ApiCampaignsIdRouteWithChildren,
  ApiCampaignsProcessDueDraftsRoute: ApiCampaignsProcessDueDraftsRoute,
  ApiCampaignsSchedulerRoute: ApiCampaignsSchedulerRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiDirectoriesAddRoute: ApiDirectoriesAddRoute,
  ApiDirectoriesEnrichRoute: ApiDirectoriesEnrichRoute,
  ApiDirectoriesSearchRoute: ApiDirectoriesSearchRoute,
  ApiEmailSendRoute: ApiEmailSendRoute,
  ApiEmailTestSmtpRoute: ApiEmailTestSmtpRoute,
  ApiKeywordsIdRoute: ApiKeywordsIdRoute,
  ApiKeywordsGenerateRoute: ApiKeywordsGenerateRoute,
  ApiLinkedinGeneratePostRoute: ApiLinkedinGeneratePostRoute,
  ApiLinkedinSearchRoute: ApiLinkedinSearchRoute,
  ApiPipelineEnrichRoute: ApiPipelineEnrichRoute,
  ApiPipelineImportRoute: ApiPipelineImportRoute,
  ApiPipelineLeadsRoute: ApiPipelineLeadsRouteWithChildren,
  ApiRedditPostsRoute: ApiRedditPostsRouteWithChildren,
  ApiRedditSearchRoute: ApiRedditSearchRoute,
  ApiRedditSuggestRoute: ApiRedditSuggestRoute,
  ApiRedditToPipelineRoute: ApiRedditToPipelineRoute,
  ApiSubredditsIdRoute: ApiSubredditsIdRoute,
  ApiTemplatesIdRoute: ApiTemplatesIdRoute,
  ApiWebhooksEmailInboundRoute: ApiWebhooksEmailInboundRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
  ApiWorkspaceGenerateDescriptionRoute: ApiWorkspaceGenerateDescriptionRoute,
  ApiBlogIndexRoute: ApiBlogIndexRoute,
  ApiCampaignsIndexRoute: ApiCampaignsIndexRoute,
  ApiKeywordsIndexRoute: ApiKeywordsIndexRoute,
  ApiPipelineIndexRoute: ApiPipelineIndexRoute,
  ApiSubredditsIndexRoute: ApiSubredditsIndexRoute,
  ApiTemplatesIndexRoute: ApiTemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
