/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as WorkspaceIdRouteRouteImport } from './routes/$workspaceId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIdIndexRouteImport } from './routes/$workspaceId/index'
import { Route as WorkspaceIdRedditRouteImport } from './routes/$workspaceId/reddit'
import { Route as WorkspaceIdPipelineRouteImport } from './routes/$workspaceId/pipeline'
import { Route as WorkspaceIdLinkedinRouteImport } from './routes/$workspaceId/linkedin'
import { Route as WorkspaceIdKeywordsRouteImport } from './routes/$workspaceId/keywords'
import { Route as WorkspaceIdBlogRouteImport } from './routes/$workspaceId/blog'
import { Route as WorkspaceIdAgentRouteImport } from './routes/$workspaceId/agent'
import { Route as WorkspaceIdSettingsRouteRouteImport } from './routes/$workspaceId/settings/route'
import { Route as ApiSubredditsIndexRouteImport } from './routes/api/subreddits/index'
import { Route as ApiPipelineIndexRouteImport } from './routes/api/pipeline/index'
import { Route as ApiKeywordsIndexRouteImport } from './routes/api/keywords/index'
import { Route as ApiBlogIndexRouteImport } from './routes/api/blog/index'
import { Route as WorkspaceIdSettingsIndexRouteImport } from './routes/$workspaceId/settings/index'
import { Route as ApiWorkspaceGenerateDescriptionRouteImport } from './routes/api/workspace/generate-description'
import { Route as ApiSubredditsIdRouteImport } from './routes/api/subreddits/$id'
import { Route as ApiRedditSuggestRouteImport } from './routes/api/reddit/suggest'
import { Route as ApiRedditSearchRouteImport } from './routes/api/reddit/search'
import { Route as ApiRedditPostsRouteImport } from './routes/api/reddit/posts'
import { Route as ApiPipelineLeadsRouteImport } from './routes/api/pipeline/leads'
import { Route as ApiLinkedinSearchRouteImport } from './routes/api/linkedin/search'
import { Route as ApiLinkedinGeneratePostRouteImport } from './routes/api/linkedin/generate-post'
import { Route as ApiKeywordsGenerateRouteImport } from './routes/api/keywords/generate'
import { Route as ApiKeywordsIdRouteImport } from './routes/api/keywords/$id'
import { Route as ApiEmailSendRouteImport } from './routes/api/email/send'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard/stats'
import { Route as ApiBlogGenerateRouteImport } from './routes/api/blog/generate'
import { Route as ApiBlogIdRouteImport } from './routes/api/blog/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentRunRouteImport } from './routes/api/agent/run'
import { Route as WorkspaceIdSettingsWorkspaceRouteImport } from './routes/$workspaceId/settings/workspace'
import { Route as WorkspaceIdSettingsProfileRouteImport } from './routes/$workspaceId/settings/profile'
import { Route as WorkspaceIdSettingsDangerRouteImport } from './routes/$workspaceId/settings/danger'
import { Route as WorkspaceIdSettingsBillingRouteImport } from './routes/$workspaceId/settings/billing'
import { Route as ApiPipelineLeadsIdRouteImport } from './routes/api/pipeline/leads.$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRouteRoute = WorkspaceIdRouteRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdIndexRoute = WorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdRedditRoute = WorkspaceIdRedditRouteImport.update({
  id: '/reddit',
  path: '/reddit',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdPipelineRoute = WorkspaceIdPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdLinkedinRoute = WorkspaceIdLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdKeywordsRoute = WorkspaceIdKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdBlogRoute = WorkspaceIdBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdAgentRoute = WorkspaceIdAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdSettingsRouteRoute =
  WorkspaceIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const ApiSubredditsIndexRoute = ApiSubredditsIndexRouteImport.update({
  id: '/api/subreddits/',
  path: '/api/subreddits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineIndexRoute = ApiPipelineIndexRouteImport.update({
  id: '/api/pipeline/',
  path: '/api/pipeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsIndexRoute = ApiKeywordsIndexRouteImport.update({
  id: '/api/keywords/',
  path: '/api/keywords/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIndexRoute = ApiBlogIndexRouteImport.update({
  id: '/api/blog/',
  path: '/api/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdSettingsIndexRoute =
  WorkspaceIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const ApiWorkspaceGenerateDescriptionRoute =
  ApiWorkspaceGenerateDescriptionRouteImport.update({
    id: '/api/workspace/generate-description',
    path: '/api/workspace/generate-description',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSubredditsIdRoute = ApiSubredditsIdRouteImport.update({
  id: '/api/subreddits/$id',
  path: '/api/subreddits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditSuggestRoute = ApiRedditSuggestRouteImport.update({
  id: '/api/reddit/suggest',
  path: '/api/reddit/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditSearchRoute = ApiRedditSearchRouteImport.update({
  id: '/api/reddit/search',
  path: '/api/reddit/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedditPostsRoute = ApiRedditPostsRouteImport.update({
  id: '/api/reddit/posts',
  path: '/api/reddit/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineLeadsRoute = ApiPipelineLeadsRouteImport.update({
  id: '/api/pipeline/leads',
  path: '/api/pipeline/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinSearchRoute = ApiLinkedinSearchRouteImport.update({
  id: '/api/linkedin/search',
  path: '/api/linkedin/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinGeneratePostRoute = ApiLinkedinGeneratePostRouteImport.update({
  id: '/api/linkedin/generate-post',
  path: '/api/linkedin/generate-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsGenerateRoute = ApiKeywordsGenerateRouteImport.update({
  id: '/api/keywords/generate',
  path: '/api/keywords/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsIdRoute = ApiKeywordsIdRouteImport.update({
  id: '/api/keywords/$id',
  path: '/api/keywords/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSendRoute = ApiEmailSendRouteImport.update({
  id: '/api/email/send',
  path: '/api/email/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogGenerateRoute = ApiBlogGenerateRouteImport.update({
  id: '/api/blog/generate',
  path: '/api/blog/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIdRoute = ApiBlogIdRouteImport.update({
  id: '/api/blog/$id',
  path: '/api/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRunRoute = ApiAgentRunRouteImport.update({
  id: '/api/agent/run',
  path: '/api/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdSettingsWorkspaceRoute =
  WorkspaceIdSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdSettingsProfileRoute =
  WorkspaceIdSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdSettingsDangerRoute =
  WorkspaceIdSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspaceIdSettingsBillingRoute =
  WorkspaceIdSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => WorkspaceIdSettingsRouteRoute,
  } as any)
const ApiPipelineLeadsIdRoute = ApiPipelineLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPipelineLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRouteRouteWithChildren
  '/$workspaceId/agent': typeof WorkspaceIdAgentRoute
  '/$workspaceId/blog': typeof WorkspaceIdBlogRoute
  '/$workspaceId/keywords': typeof WorkspaceIdKeywordsRoute
  '/$workspaceId/linkedin': typeof WorkspaceIdLinkedinRoute
  '/$workspaceId/pipeline': typeof WorkspaceIdPipelineRoute
  '/$workspaceId/reddit': typeof WorkspaceIdRedditRoute
  '/$workspaceId/': typeof WorkspaceIdIndexRoute
  '/$workspaceId/settings/billing': typeof WorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/danger': typeof WorkspaceIdSettingsDangerRoute
  '/$workspaceId/settings/profile': typeof WorkspaceIdSettingsProfileRoute
  '/$workspaceId/settings/workspace': typeof WorkspaceIdSettingsWorkspaceRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/generate': typeof ApiBlogGenerateRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRoute
  '/api/keywords/generate': typeof ApiKeywordsGenerateRoute
  '/api/linkedin/generate-post': typeof ApiLinkedinGeneratePostRoute
  '/api/linkedin/search': typeof ApiLinkedinSearchRoute
  '/api/pipeline/leads': typeof ApiPipelineLeadsRouteWithChildren
  '/api/reddit/posts': typeof ApiRedditPostsRoute
  '/api/reddit/search': typeof ApiRedditSearchRoute
  '/api/reddit/suggest': typeof ApiRedditSuggestRoute
  '/api/subreddits/$id': typeof ApiSubredditsIdRoute
  '/api/workspace/generate-description': typeof ApiWorkspaceGenerateDescriptionRoute
  '/$workspaceId/settings/': typeof WorkspaceIdSettingsIndexRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/keywords/': typeof ApiKeywordsIndexRoute
  '/api/pipeline/': typeof ApiPipelineIndexRoute
  '/api/subreddits/': typeof ApiSubredditsIndexRoute
  '/api/pipeline/leads/$id': typeof ApiPipelineLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$workspaceId/agent': typeof WorkspaceIdAgentRoute
  '/$workspaceId/blog': typeof WorkspaceIdBlogRoute
  '/$workspaceId/keywords': typeof WorkspaceIdKeywordsRoute
  '/$workspaceId/linkedin': typeof WorkspaceIdLinkedinRoute
  '/$workspaceId/pipeline': typeof WorkspaceIdPipelineRoute
  '/$workspaceId/reddit': typeof WorkspaceIdRedditRoute
  '/$workspaceId': typeof WorkspaceIdIndexRoute
  '/$workspaceId/settings/billing': typeof WorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/danger': typeof WorkspaceIdSettingsDangerRoute
  '/$workspaceId/settings/profile': typeof WorkspaceIdSettingsProfileRoute
  '/$workspaceId/settings/workspace': typeof WorkspaceIdSettingsWorkspaceRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/generate': typeof ApiBlogGenerateRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRoute
  '/api/keywords/generate': typeof ApiKeywordsGenerateRoute
  '/api/linkedin/generate-post': typeof ApiLinkedinGeneratePostRoute
  '/api/linkedin/search': typeof ApiLinkedinSearchRoute
  '/api/pipeline/leads': typeof ApiPipelineLeadsRouteWithChildren
  '/api/reddit/posts': typeof ApiRedditPostsRoute
  '/api/reddit/search': typeof ApiRedditSearchRoute
  '/api/reddit/suggest': typeof ApiRedditSuggestRoute
  '/api/subreddits/$id': typeof ApiSubredditsIdRoute
  '/api/workspace/generate-description': typeof ApiWorkspaceGenerateDescriptionRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsIndexRoute
  '/api/blog': typeof ApiBlogIndexRoute
  '/api/keywords': typeof ApiKeywordsIndexRoute
  '/api/pipeline': typeof ApiPipelineIndexRoute
  '/api/subreddits': typeof ApiSubredditsIndexRoute
  '/api/pipeline/leads/$id': typeof ApiPipelineLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$workspaceId/settings': typeof WorkspaceIdSettingsRouteRouteWithChildren
  '/$workspaceId/agent': typeof WorkspaceIdAgentRoute
  '/$workspaceId/blog': typeof WorkspaceIdBlogRoute
  '/$workspaceId/keywords': typeof WorkspaceIdKeywordsRoute
  '/$workspaceId/linkedin': typeof WorkspaceIdLinkedinRoute
  '/$workspaceId/pipeline': typeof WorkspaceIdPipelineRoute
  '/$workspaceId/reddit': typeof WorkspaceIdRedditRoute
  '/$workspaceId/': typeof WorkspaceIdIndexRoute
  '/$workspaceId/settings/billing': typeof WorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/danger': typeof WorkspaceIdSettingsDangerRoute
  '/$workspaceId/settings/profile': typeof WorkspaceIdSettingsProfileRoute
  '/$workspaceId/settings/workspace': typeof WorkspaceIdSettingsWorkspaceRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$id': typeof ApiBlogIdRoute
  '/api/blog/generate': typeof ApiBlogGenerateRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRoute
  '/api/keywords/generate': typeof ApiKeywordsGenerateRoute
  '/api/linkedin/generate-post': typeof ApiLinkedinGeneratePostRoute
  '/api/linkedin/search': typeof ApiLinkedinSearchRoute
  '/api/pipeline/leads': typeof ApiPipelineLeadsRouteWithChildren
  '/api/reddit/posts': typeof ApiRedditPostsRoute
  '/api/reddit/search': typeof ApiRedditSearchRoute
  '/api/reddit/suggest': typeof ApiRedditSuggestRoute
  '/api/subreddits/$id': typeof ApiSubredditsIdRoute
  '/api/workspace/generate-description': typeof ApiWorkspaceGenerateDescriptionRoute
  '/$workspaceId/settings/': typeof WorkspaceIdSettingsIndexRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/keywords/': typeof ApiKeywordsIndexRoute
  '/api/pipeline/': typeof ApiPipelineIndexRoute
  '/api/subreddits/': typeof ApiSubredditsIndexRoute
  '/api/pipeline/leads/$id': typeof ApiPipelineLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceId'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/$workspaceId/settings'
    | '/$workspaceId/agent'
    | '/$workspaceId/blog'
    | '/$workspaceId/keywords'
    | '/$workspaceId/linkedin'
    | '/$workspaceId/pipeline'
    | '/$workspaceId/reddit'
    | '/$workspaceId/'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/danger'
    | '/$workspaceId/settings/profile'
    | '/$workspaceId/settings/workspace'
    | '/api/agent/run'
    | '/api/auth/$'
    | '/api/blog/$id'
    | '/api/blog/generate'
    | '/api/dashboard/stats'
    | '/api/email/send'
    | '/api/keywords/$id'
    | '/api/keywords/generate'
    | '/api/linkedin/generate-post'
    | '/api/linkedin/search'
    | '/api/pipeline/leads'
    | '/api/reddit/posts'
    | '/api/reddit/search'
    | '/api/reddit/suggest'
    | '/api/subreddits/$id'
    | '/api/workspace/generate-description'
    | '/$workspaceId/settings/'
    | '/api/blog/'
    | '/api/keywords/'
    | '/api/pipeline/'
    | '/api/subreddits/'
    | '/api/pipeline/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/$workspaceId/agent'
    | '/$workspaceId/blog'
    | '/$workspaceId/keywords'
    | '/$workspaceId/linkedin'
    | '/$workspaceId/pipeline'
    | '/$workspaceId/reddit'
    | '/$workspaceId'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/danger'
    | '/$workspaceId/settings/profile'
    | '/$workspaceId/settings/workspace'
    | '/api/agent/run'
    | '/api/auth/$'
    | '/api/blog/$id'
    | '/api/blog/generate'
    | '/api/dashboard/stats'
    | '/api/email/send'
    | '/api/keywords/$id'
    | '/api/keywords/generate'
    | '/api/linkedin/generate-post'
    | '/api/linkedin/search'
    | '/api/pipeline/leads'
    | '/api/reddit/posts'
    | '/api/reddit/search'
    | '/api/reddit/suggest'
    | '/api/subreddits/$id'
    | '/api/workspace/generate-description'
    | '/$workspaceId/settings'
    | '/api/blog'
    | '/api/keywords'
    | '/api/pipeline'
    | '/api/subreddits'
    | '/api/pipeline/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/$workspaceId'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/$workspaceId/settings'
    | '/$workspaceId/agent'
    | '/$workspaceId/blog'
    | '/$workspaceId/keywords'
    | '/$workspaceId/linkedin'
    | '/$workspaceId/pipeline'
    | '/$workspaceId/reddit'
    | '/$workspaceId/'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/danger'
    | '/$workspaceId/settings/profile'
    | '/$workspaceId/settings/workspace'
    | '/api/agent/run'
    | '/api/auth/$'
    | '/api/blog/$id'
    | '/api/blog/generate'
    | '/api/dashboard/stats'
    | '/api/email/send'
    | '/api/keywords/$id'
    | '/api/keywords/generate'
    | '/api/linkedin/generate-post'
    | '/api/linkedin/search'
    | '/api/pipeline/leads'
    | '/api/reddit/posts'
    | '/api/reddit/search'
    | '/api/reddit/suggest'
    | '/api/subreddits/$id'
    | '/api/workspace/generate-description'
    | '/$workspaceId/settings/'
    | '/api/blog/'
    | '/api/keywords/'
    | '/api/pipeline/'
    | '/api/subreddits/'
    | '/api/pipeline/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceIdRouteRoute: typeof WorkspaceIdRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAgentRunRoute: typeof ApiAgentRunRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlogIdRoute: typeof ApiBlogIdRoute
  ApiBlogGenerateRoute: typeof ApiBlogGenerateRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiEmailSendRoute: typeof ApiEmailSendRoute
  ApiKeywordsIdRoute: typeof ApiKeywordsIdRoute
  ApiKeywordsGenerateRoute: typeof ApiKeywordsGenerateRoute
  ApiLinkedinGeneratePostRoute: typeof ApiLinkedinGeneratePostRoute
  ApiLinkedinSearchRoute: typeof ApiLinkedinSearchRoute
  ApiPipelineLeadsRoute: typeof ApiPipelineLeadsRouteWithChildren
  ApiRedditPostsRoute: typeof ApiRedditPostsRoute
  ApiRedditSearchRoute: typeof ApiRedditSearchRoute
  ApiRedditSuggestRoute: typeof ApiRedditSuggestRoute
  ApiSubredditsIdRoute: typeof ApiSubredditsIdRoute
  ApiWorkspaceGenerateDescriptionRoute: typeof ApiWorkspaceGenerateDescriptionRoute
  ApiBlogIndexRoute: typeof ApiBlogIndexRoute
  ApiKeywordsIndexRoute: typeof ApiKeywordsIndexRoute
  ApiPipelineIndexRoute: typeof ApiPipelineIndexRoute
  ApiSubredditsIndexRoute: typeof ApiSubredditsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId': {
      id: '/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof WorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/': {
      id: '/$workspaceId/'
      path: '/'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof WorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/reddit': {
      id: '/$workspaceId/reddit'
      path: '/reddit'
      fullPath: '/$workspaceId/reddit'
      preLoaderRoute: typeof WorkspaceIdRedditRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/pipeline': {
      id: '/$workspaceId/pipeline'
      path: '/pipeline'
      fullPath: '/$workspaceId/pipeline'
      preLoaderRoute: typeof WorkspaceIdPipelineRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/linkedin': {
      id: '/$workspaceId/linkedin'
      path: '/linkedin'
      fullPath: '/$workspaceId/linkedin'
      preLoaderRoute: typeof WorkspaceIdLinkedinRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/keywords': {
      id: '/$workspaceId/keywords'
      path: '/keywords'
      fullPath: '/$workspaceId/keywords'
      preLoaderRoute: typeof WorkspaceIdKeywordsRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/blog': {
      id: '/$workspaceId/blog'
      path: '/blog'
      fullPath: '/$workspaceId/blog'
      preLoaderRoute: typeof WorkspaceIdBlogRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/agent': {
      id: '/$workspaceId/agent'
      path: '/agent'
      fullPath: '/$workspaceId/agent'
      preLoaderRoute: typeof WorkspaceIdAgentRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/$workspaceId/settings': {
      id: '/$workspaceId/settings'
      path: '/settings'
      fullPath: '/$workspaceId/settings'
      preLoaderRoute: typeof WorkspaceIdSettingsRouteRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/api/subreddits/': {
      id: '/api/subreddits/'
      path: '/api/subreddits'
      fullPath: '/api/subreddits/'
      preLoaderRoute: typeof ApiSubredditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/': {
      id: '/api/pipeline/'
      path: '/api/pipeline'
      fullPath: '/api/pipeline/'
      preLoaderRoute: typeof ApiPipelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords/': {
      id: '/api/keywords/'
      path: '/api/keywords'
      fullPath: '/api/keywords/'
      preLoaderRoute: typeof ApiKeywordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/': {
      id: '/api/blog/'
      path: '/api/blog'
      fullPath: '/api/blog/'
      preLoaderRoute: typeof ApiBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/settings/': {
      id: '/$workspaceId/settings/'
      path: '/'
      fullPath: '/$workspaceId/settings/'
      preLoaderRoute: typeof WorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/api/workspace/generate-description': {
      id: '/api/workspace/generate-description'
      path: '/api/workspace/generate-description'
      fullPath: '/api/workspace/generate-description'
      preLoaderRoute: typeof ApiWorkspaceGenerateDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subreddits/$id': {
      id: '/api/subreddits/$id'
      path: '/api/subreddits/$id'
      fullPath: '/api/subreddits/$id'
      preLoaderRoute: typeof ApiSubredditsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/suggest': {
      id: '/api/reddit/suggest'
      path: '/api/reddit/suggest'
      fullPath: '/api/reddit/suggest'
      preLoaderRoute: typeof ApiRedditSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/search': {
      id: '/api/reddit/search'
      path: '/api/reddit/search'
      fullPath: '/api/reddit/search'
      preLoaderRoute: typeof ApiRedditSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reddit/posts': {
      id: '/api/reddit/posts'
      path: '/api/reddit/posts'
      fullPath: '/api/reddit/posts'
      preLoaderRoute: typeof ApiRedditPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline/leads': {
      id: '/api/pipeline/leads'
      path: '/api/pipeline/leads'
      fullPath: '/api/pipeline/leads'
      preLoaderRoute: typeof ApiPipelineLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/search': {
      id: '/api/linkedin/search'
      path: '/api/linkedin/search'
      fullPath: '/api/linkedin/search'
      preLoaderRoute: typeof ApiLinkedinSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/generate-post': {
      id: '/api/linkedin/generate-post'
      path: '/api/linkedin/generate-post'
      fullPath: '/api/linkedin/generate-post'
      preLoaderRoute: typeof ApiLinkedinGeneratePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords/generate': {
      id: '/api/keywords/generate'
      path: '/api/keywords/generate'
      fullPath: '/api/keywords/generate'
      preLoaderRoute: typeof ApiKeywordsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords/$id': {
      id: '/api/keywords/$id'
      path: '/api/keywords/$id'
      fullPath: '/api/keywords/$id'
      preLoaderRoute: typeof ApiKeywordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/send': {
      id: '/api/email/send'
      path: '/api/email/send'
      fullPath: '/api/email/send'
      preLoaderRoute: typeof ApiEmailSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/generate': {
      id: '/api/blog/generate'
      path: '/api/blog/generate'
      fullPath: '/api/blog/generate'
      preLoaderRoute: typeof ApiBlogGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$id': {
      id: '/api/blog/$id'
      path: '/api/blog/$id'
      fullPath: '/api/blog/$id'
      preLoaderRoute: typeof ApiBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/run': {
      id: '/api/agent/run'
      path: '/api/agent/run'
      fullPath: '/api/agent/run'
      preLoaderRoute: typeof ApiAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/settings/workspace': {
      id: '/$workspaceId/settings/workspace'
      path: '/workspace'
      fullPath: '/$workspaceId/settings/workspace'
      preLoaderRoute: typeof WorkspaceIdSettingsWorkspaceRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/settings/profile': {
      id: '/$workspaceId/settings/profile'
      path: '/profile'
      fullPath: '/$workspaceId/settings/profile'
      preLoaderRoute: typeof WorkspaceIdSettingsProfileRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/settings/danger': {
      id: '/$workspaceId/settings/danger'
      path: '/danger'
      fullPath: '/$workspaceId/settings/danger'
      preLoaderRoute: typeof WorkspaceIdSettingsDangerRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/$workspaceId/settings/billing': {
      id: '/$workspaceId/settings/billing'
      path: '/billing'
      fullPath: '/$workspaceId/settings/billing'
      preLoaderRoute: typeof WorkspaceIdSettingsBillingRouteImport
      parentRoute: typeof WorkspaceIdSettingsRouteRoute
    }
    '/api/pipeline/leads/$id': {
      id: '/api/pipeline/leads/$id'
      path: '/$id'
      fullPath: '/api/pipeline/leads/$id'
      preLoaderRoute: typeof ApiPipelineLeadsIdRouteImport
      parentRoute: typeof ApiPipelineLeadsRoute
    }
  }
}

interface WorkspaceIdSettingsRouteRouteChildren {
  WorkspaceIdSettingsBillingRoute: typeof WorkspaceIdSettingsBillingRoute
  WorkspaceIdSettingsDangerRoute: typeof WorkspaceIdSettingsDangerRoute
  WorkspaceIdSettingsProfileRoute: typeof WorkspaceIdSettingsProfileRoute
  WorkspaceIdSettingsWorkspaceRoute: typeof WorkspaceIdSettingsWorkspaceRoute
  WorkspaceIdSettingsIndexRoute: typeof WorkspaceIdSettingsIndexRoute
}

const WorkspaceIdSettingsRouteRouteChildren: WorkspaceIdSettingsRouteRouteChildren =
  {
    WorkspaceIdSettingsBillingRoute: WorkspaceIdSettingsBillingRoute,
    WorkspaceIdSettingsDangerRoute: WorkspaceIdSettingsDangerRoute,
    WorkspaceIdSettingsProfileRoute: WorkspaceIdSettingsProfileRoute,
    WorkspaceIdSettingsWorkspaceRoute: WorkspaceIdSettingsWorkspaceRoute,
    WorkspaceIdSettingsIndexRoute: WorkspaceIdSettingsIndexRoute,
  }

const WorkspaceIdSettingsRouteRouteWithChildren =
  WorkspaceIdSettingsRouteRoute._addFileChildren(
    WorkspaceIdSettingsRouteRouteChildren,
  )

interface WorkspaceIdRouteRouteChildren {
  WorkspaceIdSettingsRouteRoute: typeof WorkspaceIdSettingsRouteRouteWithChildren
  WorkspaceIdAgentRoute: typeof WorkspaceIdAgentRoute
  WorkspaceIdBlogRoute: typeof WorkspaceIdBlogRoute
  WorkspaceIdKeywordsRoute: typeof WorkspaceIdKeywordsRoute
  WorkspaceIdLinkedinRoute: typeof WorkspaceIdLinkedinRoute
  WorkspaceIdPipelineRoute: typeof WorkspaceIdPipelineRoute
  WorkspaceIdRedditRoute: typeof WorkspaceIdRedditRoute
  WorkspaceIdIndexRoute: typeof WorkspaceIdIndexRoute
}

const WorkspaceIdRouteRouteChildren: WorkspaceIdRouteRouteChildren = {
  WorkspaceIdSettingsRouteRoute: WorkspaceIdSettingsRouteRouteWithChildren,
  WorkspaceIdAgentRoute: WorkspaceIdAgentRoute,
  WorkspaceIdBlogRoute: WorkspaceIdBlogRoute,
  WorkspaceIdKeywordsRoute: WorkspaceIdKeywordsRoute,
  WorkspaceIdLinkedinRoute: WorkspaceIdLinkedinRoute,
  WorkspaceIdPipelineRoute: WorkspaceIdPipelineRoute,
  WorkspaceIdRedditRoute: WorkspaceIdRedditRoute,
  WorkspaceIdIndexRoute: WorkspaceIdIndexRoute,
}

const WorkspaceIdRouteRouteWithChildren =
  WorkspaceIdRouteRoute._addFileChildren(WorkspaceIdRouteRouteChildren)

interface ApiPipelineLeadsRouteChildren {
  ApiPipelineLeadsIdRoute: typeof ApiPipelineLeadsIdRoute
}

const ApiPipelineLeadsRouteChildren: ApiPipelineLeadsRouteChildren = {
  ApiPipelineLeadsIdRoute: ApiPipelineLeadsIdRoute,
}

const ApiPipelineLeadsRouteWithChildren =
  ApiPipelineLeadsRoute._addFileChildren(ApiPipelineLeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceIdRouteRoute: WorkspaceIdRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAgentRunRoute: ApiAgentRunRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlogIdRoute: ApiBlogIdRoute,
  ApiBlogGenerateRoute: ApiBlogGenerateRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiEmailSendRoute: ApiEmailSendRoute,
  ApiKeywordsIdRoute: ApiKeywordsIdRoute,
  ApiKeywordsGenerateRoute: ApiKeywordsGenerateRoute,
  ApiLinkedinGeneratePostRoute: ApiLinkedinGeneratePostRoute,
  ApiLinkedinSearchRoute: ApiLinkedinSearchRoute,
  ApiPipelineLeadsRoute: ApiPipelineLeadsRouteWithChildren,
  ApiRedditPostsRoute: ApiRedditPostsRoute,
  ApiRedditSearchRoute: ApiRedditSearchRoute,
  ApiRedditSuggestRoute: ApiRedditSuggestRoute,
  ApiSubredditsIdRoute: ApiSubredditsIdRoute,
  ApiWorkspaceGenerateDescriptionRoute: ApiWorkspaceGenerateDescriptionRoute,
  ApiBlogIndexRoute: ApiBlogIndexRoute,
  ApiKeywordsIndexRoute: ApiKeywordsIndexRoute,
  ApiPipelineIndexRoute: ApiPipelineIndexRoute,
  ApiSubredditsIndexRoute: ApiSubredditsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
